### ISSUE TITLE
Expose updatedAt in listAccounts endpoint

### ISSUE THREAD

**Issue by Pagebakers** [better-auth/better-auth#1039]
### Is this suited for github?

- [X] Yes, this is suited for github

### Is your feature request related to a problem? Please describe.

I would like the listAccounts endpoint to return the updatedAt timestamp, so I can use this to show the user when their password has last been changed for example.

### Describe the solution you'd like

Return the timestamps here: https://github.com/better-auth/better-auth/blob/main/packages/better-auth/src/api/routes/account.ts#L52

### Describe alternatives you've considered

Alternative is to query this myself, but I would rather use the built in client.

### Additional context

I'm happy to open a PR for this if it's approved.

**Comment by Bekacru** [comment]
Hey yeah we can add this. Feel free to open a PR!

**Comment by daveycodez** [comment]
It would be great if we could also list the emails in listAccounts as well so in the settings page we can show users which accounts they have connected for each provider. I assume this would just be available in the access_token field which we could use Jose to decode. I'm working on a better-auth-ui package that comes with settings cards for managing providers, would like to show users what accounts they have connected for each provider

**Comment by Pagebakers** [comment]
Awesome! appreciate the fast turn around.
