### ISSUE TITLE
Using Drizzle fails on creation due to unsupported use of `returning()` with MySQL

### ISSUE THREAD

**Issue by inducingchaos** [better-auth/better-auth#105]
MySQL itself doesn’t have native support for RETURNING after using INSERT:

https://orm.drizzle.team/docs/insert#insert-returningid

The adapter is using the code for PostgreSQL and SQLite here:

https://github.com/better-auth/better-auth/blob/41d81565f5eeefbca85e356bc793639d4d4c5381/packages/better-auth/src/adapters/drizzle-adapter/index.ts#L93

**Comment by Bekacru** [comment]
fixed
