### ISSUE TITLE
After the upgrade, logging in and returning shows INVALID_ORIGIN.

### ISSUE THREAD

**Issue by hellokaton** [better-auth/better-auth#1066]
### Is this suited for github?

- [X] Yes, this is suited for github

### To Reproduce

I didn't make any changes, I just encountered this issue when upgrading from version `1.1.4` to version `1.1.6`

### Current vs. Expected behavior

```
/api/auth/callback/google?state=3_i8sWggoMcXSobH0Wbck5D81_f0nAph&code=4%2F0AanRRru7XcG2vj4tqW0w1Y5hhOSz2o2E4Q3GOKucPgp7La1OBn0nkq1WTmETen4Fwl9NNA&scope=email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+openid&authuser=0&prompt=none
```

```json
{
  "message": "Invalid origin",
  "code": "INVALID_ORIGIN"
}
```

### What version of Better Auth are you using?

1.1.6

### Provide environment information

```bash
- OS: Server Environment Bun
- Brower: Chrome
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript
trustedOrigins: [env.BETTER_AUTH_URL],
socialProviders: {
    google: {
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
    }
},
```

**Comment by productdevbook** [comment]
OIDC Provider with the same error on my installation.
