### ISSUE TITLE
plugin: admin plugin

### ISSUE THREAD

**Issue by Bekacru** [better-auth/better-auth#116]
Add an admin plugin that provides functionalities for administrative tasks, such as banning users, creating users directly, and handling other related admin activities.

**Comment by Loa212** [comment]
would it be possible to add `user impersonation`  ? or should it be a separate plugin?

**Comment by Bekacru** [comment]
> would it be possible to add `user impersonation` ? or should it be a separate plugin?

yeah the admin plugin should include it
