### ISSUE TITLE
Support for Security Questions

### ISSUE THREAD

**Issue by olivebishop** [better-auth/better-auth#120]
we all know securtity questions plays a crucial role in auth , we can have a security questions integrated within better auth so that on frontend we just fetch and update based on answers that were set by the user

**Comment by luksch42** [comment]
I think we should stay with 2FA instead of security questions, as the latter are often guessable or easy to obtain. For example, in a casual conversation at a party, I could easily ask something like, 'Do you have pets?' followed by, 'What was its name?'—making it simple to uncover answers to common security questions.

**Comment by olivebishop** [comment]
@luksch42 i dont think so , take example a platform like upwork  , they have security questions .... You MIGHT BE RIGHT though !

**Comment by tklein1801** [comment]
Are there no plugins for exactly this reason? I would suggest a plugin which will create two tables (name may vary)
- `security_questions`
- `user_security_questions`

and extending the router and api to support these requirements

**Comment by olivebishop** [comment]
agree @tklein1801

**Comment by olivebishop** [comment]
@Bekacru  your take ?

**Comment by Bekacru** [comment]
> @Bekacru your take ?

I'm fine with adding it as a plugin, but I don't think there are enough use cases to justify including it as a core 2FA method. If anyone wants to give it a try, I'm happy to help and merge.

**Comment by olivebishop** [comment]
ok

**Comment by itsderinger** [comment]
FYI: "Knowledge-based authentication (KBA), sometimes referred to as **“security questions”**, is no longer recognized as an acceptable authenticator by SP 800-63" as KBA has an unacceptably high risk of successful use by an attacker ([Source](https://pages.nist.gov/800-63-FAQ/#q-b07)).

**Comment by Bekacru** [comment]
I'm going to close this issue there are currently no plans to add this on the core.
