### ISSUE TITLE
feat: Support typed additional fields on core tables

### ISSUE THREAD

**Issue by Bekacru** [better-auth/better-auth#121]
Allow custom fields to be added to the `user` and `session` tables, with potential support for `organization` as well. This functionality could be implemented as a plugin, as it requires configuration on both the client and server sides.

**Comment by emroot** [comment]
it would be interesting to take some inspiration from next-auth for this. 
https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-prisma/src/index.ts
It provides enough flexibility for devs to override those function and let them do what they need. 
I'm currently using next-auth and override some of those functions to populate extra columns.
example usage with next-auth
```
...adapter: {
    ...PrismaAdapter(prismaClient),
    createUser(user) {
      return db.user.create({
        data: {
          ...user,
          customColumn: 'test'
        },
      });
    },

    deleteUser(userId) {
      return db.user.update({
        where: {
          id: userId,
        },
        data: {
          deletedAt: new Date(),
          isDeleted: true,
        },
      });
    },
    async getUser(id) {
      return db.user.findFirst({
        where: { id, isDeleted: false },
      });
    },
    async getUserByEmail(email) {
      return db.user.findFirst({
        where: { email, isDeleted: false },
      });
    },
    // },
  },
```

**Comment by andrewcoelho** [comment]
@Bekacru are there any plans for supporting this on organizations as well?

**Comment by bhaleraosaurabh** [comment]
@Bekacru I have the same question as @andrewcoelho. 

At the moment, I've just added new columns to the table in my prisma schema as optional fields and created a separate endpoint through which I'm able to use the additional columns for updating the organization.

It would be nice if we could extend the schema for plugins like organization. Came here looking for an answer to the same question as I need to extend the organization table. Are there any plans to support this feature?
