### ISSUE TITLE
Possibly change user core table from name to firstname, lastname and username

### ISSUE THREAD

**Issue by xcaeser** [better-auth/better-auth#13]
the docs showcasing the user table:
[User table](https://www.better-auth.com/#user-table)

Proposal to update it to become:
username, firstname, lastname.

username being a potential combination of first letters if First and lastnames.

Potential refactoring, a lot.

**Comment by xKesvaL** [comment]
I really do think the only thing that could *"need"* change is `name` -> `displayName`, as that is litteraly what it is.
First name and last name should be up to the user to implement.

**Comment by Bekacru** [comment]
> I really do think the only thing that could _"need"_ change is `name` -> `displayName`, as that is litteraly what it is. First name and last name should be up to the user to implement.

Since `name` is already used by next-auth, which is probably one of the most widely adopted library in the ecosystem, it makes sense to conform to that. But, I think `displayName` makes more sense too.

**Comment by xcaeser** [comment]
I think we can all agree that the goal of better-auth is to be better than next-auth (which sucks to push you to use clerk)

**Comment by Bekacru** [comment]
Since user fields need to be mapped to the user information returned by OAuth, we don’t always receive both `firstName` and `lastName`. And for using display name instead, OAuth2 Spec profile provides a `name` field for the full name, rather than a `displayName` or something similar. Seems fair enough to conform to that. If someone wants to have separate `firstName` and `lastName` fields, they can use additional fields for now. We also plan to allow users to define non-mandatory user fields themselves in the future. Given this, making a change now doesn’t make much sense, so I’ll close this issue.

**Comment by Fefedu973** [comment]
It would be nice tbh to have theses fields

**Comment by Bekacru** [comment]
> It would be nice tbh to have theses fields

you could still have them as additional fields

**Comment by Fefedu973** [comment]
How can I do that please?

**Comment by luksch42** [comment]
> How can I do that please?

Here are the docs: 
https://www.better-auth.com/docs/concepts/database#extending-core-schema

**Comment by Fefedu973** [comment]
Thanks!

**Comment by Fefedu973** [comment]
And how can i integrate it directly with the Oauth response ? Thanks

**Comment by Bekacru** [comment]
> And how can i integrate it directly with the Oauth response ? Thanks

you can provide custom `getUserInfo` function for each provider. But we should have a better solution soon since that'd require you to fetch user data from the provider or parse the idToken yourself. There is already open issue #371

**Comment by Bekacru** [comment]
will give it a priority the coming week :)

**Comment by Fefedu973** [comment]
Nice thanks !

**Comment by Fefedu973** [comment]
Hey now that it is implemented could you please explain how to use it. I want to have separated fields for firstname and lastname, I use google and microsoft oauth which both provides these fields but idk how to link them to an additional field. thanks !
