### ISSUE TITLE
feat: add a change email flow

### ISSUE THREAD

**Issue by eNiiju** [better-auth/better-auth#136]
A user requesting to change their email address should first be confirmed by the old email address (if this address is verified). Then, We could call `sendVerificationEmail` for the new email address if we want to.

**Comment by niijux** [comment]
Shouldn't there be an option to first confirm the change by the old email address, in case the account got compromised? (only if that old email address was verified of course)

**Comment by Bekacru** [comment]
just updated the docs. The flow is

- User requests to change their email.
- A verification link is sent to their current email address.
- The user clicks the link, which contains a token with the new email in its payload.
- The email field is updated, and a verification email is sent to the new address.

**Comment by niijux** [comment]
Thanks for the update.
I've tried it and it looks nice, but currently the verification link to the current email address is still sent even if this address hasn't been verified.
If a user entered a wrong email address at first, they are blocked and can't change email now.

**Comment by Bekacru** [comment]
thanks. good point. now if email isn't verified the email will be changed in place withtout requireing verification process.
