### ISSUE TITLE
Module '"better-auth"' has no exported member 'createAuthMiddelware'.ts(2305)

### ISSUE THREAD

**Issue by zhaopengme** [better-auth/better-auth#138]
Module '"better-auth"' has no exported member 'createAuthMiddelware'.ts(2305)
![image](https://github.com/user-attachments/assets/50dc4abe-c670-40ea-b547-0f5157fc93ef)
thks

**Comment by Bekacru** [comment]
you need to import it from "better-auth/plugins"

**Comment by mobailabs** [comment]
this my code.
```
import myPlugin from '@/better/plugin';
import { betterAuth } from "better-auth";


export const auth = betterAuth({
 
  emailAndPassword: {
    enabled: true
  },
  plugins: [myPlugin]
});
```


plugin code
```
import { createAuthMiddelware } from "better-auth/plugins";

const myPlugin = {
  id: "my-plugin",
  middleware: [
    createAuthMiddelware(async (ctx) => {
      //do something
    })
  ]
};

export default myPlugin;
```
![image](https://github.com/user-attachments/assets/5bf8da60-580f-4188-8a75-75a2c3d3343e)


from 0.3.3 to 0.3.5-beta.3 

still error.

**Comment by Bekacru** [comment]
The API had slight changes, and the doc was not updated. I've just updated the doc.

https://www.better-auth.com/docs/concepts/plugins#middleware

**Comment by mobailabs** [comment]
ok, I'll try it later

**Comment by MattheousDT** [comment]
Typo. `createAuthMiddelware` should be `createAuthMiddleware`

**Comment by Bekacru** [comment]
this should be fixed. feel free to re-open if not.
