### ISSUE TITLE
Linking credentials to an existing social account results in “User already exists”

### ISSUE THREAD

**Issue by PawelPotempa** [better-auth/better-auth#146]
Currently, if a user signs in using social login (I’ve tested with Google), and then attempts to create a credentials-based account with the same email, a `400 User already exists` error is returned instead of linking the accounts. This works fine in the reverse scenario, where a social login is attached to an existing credentials-based account.

I’m not sure if this is the intended behavior, but I wanted to raise it in case it’s an issue. Apologies if there’s something I’m missing!

**Comment by Bekacru** [comment]
yeah, that’s intentional. To add a credential account, use the `user.setPassword` method instead. It'll set the password and create a credential account for the user.

**Comment by PawelPotempa** [comment]
Got it, thanks for the clarification! However, this raises a question regarding user experience.

If I understand the `user.setPassword` method correctly, it only makes sense to use it when the user is already signed in. Wouldn’t it make sense to also allow the user to create a credential account via the password reset flow, if they initially signed up using a social login? If no user with the email exists, it would continue to ignore the reset attempt, as it currently does.

Right now, if a user inputs their social account email in the password reset form, the email with the reset link is sent, the user can visit the link and attempt to reset the password, however, the reset attempt fails because no credential account exists. It might feel more intuitive if this process allowed the user to set up a password, creating a credential account in the process. I believe some platforms (e.g., Spotify) use a similar flow, though I haven't checked recently.

**Comment by Bekacru** [comment]
Yes, the password reset flow should allow account creation. This is a bug and it should be fixed in the next release.
