### ISSUE TITLE
The icons in docs have inconsistent sizes on mobile devices

### ISSUE THREAD

**Issue by typed-sigterm** [better-auth/better-auth#152]
![image](https://github.com/user-attachments/assets/82395ef9-27cc-4129-bd27-86633142e576)

UA: `Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Mobile Safari/537.36 EdgA/129.0.0.0`

**Comment by Bekacru** [comment]
It should be fixed. feel free to re-open if not.

**Comment by typed-sigterm** [comment]
The escaped fish ()

![image](https://github.com/user-attachments/assets/02af59d8-94ad-457c-8fa0-0b8ad1345869)
