### ISSUE TITLE
Protect API routes

### ISSUE THREAD

**Issue by moshetanzer** [better-auth/better-auth#156]
Hi,

How do you protect api routes in nuxt use better auth? Also can you do it using rbac?

**Comment by tklein1801** [comment]
@moshetanzer you can implement RBAC using [organization](https://www.better-auth.com/docs/plugins/organization#organization) and [access-control](https://www.better-auth.com/docs/plugins/organization#access-control)

**Comment by Bekacru** [comment]
You can secure it by checking the session with `auth.api.getSession`. For RBAC, you can use the `organization` plugin. If you only need `admin` and `user` roles, you can also just use the admin plugin or define custom fields instead.
