### ISSUE TITLE
Is there a test suite somewhere?

### ISSUE THREAD

**Issue by nicholaswmin** [better-auth/better-auth#17]
where's the test suite?

**Comment by Bekacru** [comment]
unit tests are co-located. Integration tests will be added soon.

**Comment by nicholaswmin** [comment]
How do I run them? Standard `npm test` from root?

**Comment by Bekacru** [comment]
> How do I run them? Standard `npm test` from root?

yeah but use pnpm

**Comment by nicholaswmin** [comment]
Yup good - thanks
