### ISSUE TITLE
Sign up with magic link

### ISSUE THREAD

**Issue by Nic13Gamer** [better-auth/better-auth#173]
Currently you can only sign in with magic links. It would be nice if we had an option to allow users to sign up using the magic link plugin.

**Comment by Bekacru** [comment]
this should work starting from `0.4.10-beta.4`.

**Comment by opswiz** [comment]
This successfully creates a user, but doesn't seem to create an account, is that expected and should be manual or did I miss anything?

@Bekacru

**Comment by InvixGG** [comment]
Has this been implemented yet?
