### ISSUE TITLE
Any plans for Redwood support?

### ISSUE THREAD

**Issue by knajjars** [better-auth/better-auth#185]

**Comment by Bekacru** [comment]
I'm not familiar with Redwood, but it should already be supported if it:

- Supports API endpoints/routes
- Works with either the Web Standard Request/Response objects or Node.js using the Node adapter.
- Supports catch-all routes.

**Comment by KelechiOdom10** [comment]
Also Redwood already has built-in auth baked into the framework. I'm not sure why we'd want to mix both!

**Comment by knajjars** [comment]
> Also Redwood already has built-in auth baked into the framework. I'm not sure why we'd want to mix both!

I think that is fair, although Redwood's auth is very limited compared to the features offered by better-auth. Also they offer setup for many different providers via their CLI (Supabase Auth, Firebase Auth, Custom, In-House solution, etc.).

**Comment by Bekacru** [comment]
We don't have plans to directly support Redwood at the moment. I think this will mostly involve providing a guide. We're always open to a PR for adding a guide on how to integrate Better Auth with Redwood. I'm going to close this as not planned.
