### ISSUE TITLE
Open Nuxt Example URL after clicking on Sveltekit Example Github

### ISSUE THREAD

**Issue by SikandarJODD** [better-auth/better-auth#19]
- when user clicks on : [Website](https://www.better-auth.com/docs/examples/svelte-kit) - View on Github 
- This Redirects to Nuxt Example : [Github](https://github.com/better-auth/better-auth/tree/main/examples/nuxt-example)
- This should redirect to Svelte-Kit Example : [Github](https://github.com/better-auth/better-auth/tree/main/examples/svelte-kit-example)
![image](https://github.com/user-attachments/assets/c64961c8-eb64-424a-95d9-d08ebb6a6185)

**Comment by Bekacru** [comment]
fixed
