### ISSUE TITLE
Cannot build NextJS app router without errors

### ISSUE THREAD

**Issue by proevilz** [better-auth/better-auth#198]
**Describe the bug**
If you use `useSession()` in a client component and then attempt to `npm run build`, it appears to try and execute a rogue `fetch()` request and errors out, since it obviously can't complete the request since there is no server at build time. 

**To Reproduce**

1. Go to clone the test repo: https://github.com/proevilz/better-auth-test
2. run `npm i && npm run build`

**Expected behavior**
Build completes without errors

**Screenshots**
![image](https://github.com/user-attachments/assets/c5651a79-071d-4ee5-9912-cdf164c94a82)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Irrelevant 
- Version: Irrelevant

**Smartphone (please complete the following information):**

^ all irrelevant 

**Additional context**

**Comment by Bekacru** [comment]
This is due to having `useSession` being called on a statically rendered path. Make sure the route is dynamic so next won't try to fetch a session on build.
