### ISSUE TITLE
Error using a different base path for socialProviders

### ISSUE THREAD

**Issue by benquan** [better-auth/better-auth#202]
**Describe the bug**
I am trying to use a different path for social providers. For what I understand, the default basePath is **/api/auth**. I am trying to remove the /api portion and just use **/auth**.

**To Reproduce**
I am using sveltekit. And my understanding is that using this auth definition would generate an automatic callback for google at /auth/callback/google

```
export const auth = betterAuth({
	basePath: '/auth',
	database: drizzleAdapter(db, {
		provider: 'sqlite' // or "mysql", "sqlite"
	}),
	emailAndPassword: {
		enabled: true
	},
	socialProviders: {
		google: {
			redirectURI: 'http://localhost:5173/auth/callback/google',
			scope: ['profile', 'email'],
			clientId: process.env.GOOGLE_ID as string,
			clientSecret: process.env.GOOGLE_SECRET as string
		}
	}
});
```
I am calling it with:
```
<button
	on:click={async () => {
		await authClient.signIn.social({
			provider: 'google'
		});
	}}
>
	Continue with Google
</button>
```

**Expected behavior**
I would expect for the google auth process to run and after the callback, control would return to the root or some defined final destination.

What I am getting is google trying to go to the defined callback **http://localhost:5173/auth/callback/google** but not finding anything there (404). I would think that by placing **basePath: '/auth',** would be enough to use that path instead of the default /api/auth

<img width="610" alt="Screenshot 2024-10-16 at 4 27 20 PM" src="https://github.com/user-attachments/assets/034d55f5-6918-4155-97a1-01ecd88e0ebc">

**Comment by Bekacru** [comment]
are you sure you have mounted the handler on the correct base path?

**Comment by Bekacru** [comment]
feel free to re-open if this isn't fixed.

**Comment by emersonlaurentino** [comment]
@Bekacru I've the same issue, but the problem is on the client, because I can set the `basePath` on the server, but when I call `signIn.social({ provider: "google" })` for example, the basePath is the default and I can't set it on the `createAuthClient`

**Comment by amosbastian** [comment]
> [@Bekacru](https://github.com/Bekacru) I've the same issue, but the problem is on the client, because I can set the `basePath` on the server, but when I call `signIn.social({ provider: "google" })` for example, the basePath is the default and I can't set it on the `createAuthClient`

I have the same problem, not sure how to make the client aware of the new path 🤔
