### ISSUE TITLE
Prisma Support for MongoDB Adapter

### ISSUE THREAD

**Issue by csyedbilal** [better-auth/better-auth#215]
I’ve considered using native MongoDB drivers or Mongoose for these features, but this adds complexity to my projects by requiring me to mix technologies. It would be much more efficient and streamlined if Prisma could handle these features natively without needing additional libraries.

**Comment by Bekacru** [comment]
mongodb should be supported on the latest release

**Comment by csyedbilal** [comment]
@Bekacru mongodb worked but

 B:\better-auth>bunx @better-auth/cli generate
√ Do you want to generate the schema to ./prisma/schema.prisma? ... yes
✔  🚀 Schema was generated successfully!                                                                                                       Better Auth

B:\huc-projects\with-better-auth>

![image](https://github.com/user-attachments/assets/218186d9-8a12-41a3-9cae-8fa02fd540ab)
![image](https://github.com/user-attachments/assets/03ba5db8-427f-4e3d-a4cb-2f2fa5b8b279)

seen there errors on schema files

**Comment by Bekacru** [comment]
yeah the cli needs to be fixed. let's leave this open until that's addressed.

**Comment by csyedbilal** [comment]
@Bekacru 
[{
	"resource": "/B:/with-better-auth/prisma/schema.prisma",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Error validating field `user` in model `Session`: The relation field `user` on model `Session` is missing an opposite relation field on the model `User`. Either run `prisma format` or add it manually.",
	"source": "Prisma",
	"startLineNumber": 35,
	"startColumn": 3,
	"endLineNumber": 36,
	"endColumn": 1
},{
	"resource": "/B:/with-better-auth/prisma/schema.prisma",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Error validating field `user` in model `Account`: The relation field `user` on model `Account` is missing an opposite relation field on the model `User`. Either run `prisma format` or add it manually.",
	"source": "Prisma",
	"startLineNumber": 45,
	"startColumn": 3,
	"endLineNumber": 46,
	"endColumn": 1
}]

 "better-auth": "^0.5.2-beta.2",
 "@better-auth/cli": "^0.5.2-beta.2",

![image](https://github.com/user-attachments/assets/5b50434b-ba98-4f13-969d-068a9995c744)
