### ISSUE TITLE
feat: magic link should verify user email

### ISSUE THREAD

**Issue by eNiiju** [better-auth/better-auth#216]
I think calling the `authClient.magicLink.verify()` function should set the `emailVerified` field in the user table to `true`. 

The action of a user clicking on this link from their email inbox is equivalent to clicking on a verification link, as the user clearly has access to the email address he provided.

Maybe this can be an optional setting, something like this :
```ts
export const auth = betterAuth({
  plugins: [
    magicLink({
      verifyEmail: true
    })
  ]
});
``` 

This would save the users' time of clicking two links that could be done at once, and of course send fewer emails.

**Comment by Bekacru** [comment]
we don't need the option. It should verify it by default.

**Comment by niijux** [comment]
Yes the option is a bit overkill, I don't think a lot of people would want to disable this. Thanks for adding it so fast !

**Comment by yigsvnsla** [comment]
hi @Bekacru @eNiiju 

I think this function is still necessary and usable. I'd like to open a discussion about the importance of this function. for instance. this helps if I want to invite a potential user without having them directly stored on my database or using it as email verification.

```ts
export const auth = betterAuth({
  plugins: [
    magicLink({
      verifyEmail: true
    })
  ]
});
```

Functionally the only way I can replicate this is by modifying the database hook. Istead I can simply use the function I'm I mentioned is necessary
