### ISSUE TITLE
Support int autoincrement IDs

### ISSUE THREAD

**Issue by ck-euan** [better-auth/better-auth#227]
**Is your feature request related to a problem? Please describe.**
I want to implement better-auth in an existing app and the users table uses an autoincrement int for the primary key and I can't change this.

**Describe the solution you'd like**
It would be great if better auth could handle both string and int IDs

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Bekacru** [comment]
This should work from v1 (v1.0.6) onward. Make sure to turn off auto-generate IDs in `advanced.generateId`. Feel free to open a new issue if you're facing problems.

**Comment by ck-euan** [comment]
@Bekacru Is there a recommended way to override the types for the user ID? Everywhere I get the session it is typed as string

**Comment by marcusleonas** [comment]
> @Bekacru Is there a recommended way to override the types for the user ID? Everywhere I get the session it is typed as string

Is there any update on this? The docs don't explain how to do this other than adding custom fields.

**Comment by Bekacru** [comment]
> Is there any update on this? The docs don't explain how to do this other than adding custom fields.

disable auto generated IDs by setting `advanced.generteId` to false and it should work

**Comment by platform-kit** [comment]
@Bekacru do you mean this would enable a different field type (i.e. INT or UUID in place of string , for user id)? Would this custom field extend to plugins etc too?

**Comment by marcusleonas** [comment]
> > Is there any update on this? The docs don't explain how to do this other than adding custom fields.
> 
> disable auto generated IDs by setting `advanced.generteId` to false and it should work

This works, but the types aren't number, they are string.
