### ISSUE TITLE
Github example doesn't work

### ISSUE THREAD

**Issue by Serpentarius13** [better-auth/better-auth#24]
I just tried to login:

![image](https://github.com/user-attachments/assets/20489f3b-5072-4b55-bf11-869d2151167e)

**Comment by Bekacru** [comment]
this should be already fixed. feel free to re-open the issue if not.

**Comment by Serpentarius13** [comment]
Its not 0-0

**Comment by Bekacru** [comment]
> Its not 0-0

where is this not working? On the official demo, examples or on your own project?

**Comment by Serpentarius13** [comment]
> > Its not 0-0
> 
> where is this not working? On the official demo, examples or on your own project?

Official demo: https://demo.better-auth.com/

**Comment by Bekacru** [comment]
this should work without any problem including in the demo and example
