### ISSUE TITLE
Server action support for auth client

### ISSUE THREAD

**Issue by mmikhan** [better-auth/better-auth#248]
it seems Server action isn't supported yet for auth client (i.e. signIn, signUp, signOut etc). For example, the following code works:

```javascript
'use client'

<button
  onClick={async () => {
    await signIn.social({
      provider: "google",
      callbackURL: "/",
    });
  }}
>Sign in with Google</button>
```

But, the same thing in a server action doesn't. No session is being stored in the database. Similarly, `await signOut()` doesn't as well.

```javascript
<form
  action={async () => {
    "use server";
    await signIn.social({
      provider: "google",
      callbackURL: "/",
    });
  }}
>
  <button type="submit">Sign in with Google</button>
</form>
```

!! Here's an [example](https://authjs.dev/getting-started/authentication/oauth) from Auth.js

**Comment by matserix** [comment]
Already implemented and documented

https://www.better-auth.com/docs/concepts/api#calling-api-endpoints-on-the-server

**Comment by mmikhan** [comment]
That's for when handling auth through an API request where you manually handle everything forward, right? But, what I am referring here is through Social login (could be Credentials login as well) and shall work by simply defining `await signIn.social()` in a server component
