### ISSUE TITLE
git clone doesn't work on windows

### ISSUE THREAD

**Issue by theMillenniumFalcon** [better-auth/better-auth#25]
![Screenshot (121)](https://github.com/user-attachments/assets/853767ba-1ee4-4fbf-a76b-eb3504350403)

The file start with * symbol is causing the error as file names starting with * are invalid on windows

As characters given below are reserved on Windows:
`<` (less than)
`>` (greater than)
`:` (colon)
`"` (double quote)
`/` (forward slash)
`\` (backslash)
`|` (vertical bar or pipe)
`?` (question mark)
`*` (asterisk)

**Comment by qamarq** [comment]
+1

**Comment by tklein1801** [comment]
Should be because of the `*auth.ts` and the file-system on windows. Not really a bug of this project or am I wrong?

**Comment by qamarq** [comment]
That's right. It's all about `*`

**Comment by theMillenniumFalcon** [comment]
Was able to clone the repository without including the `*auth.ts` file  using following command: 
```
git clone -c core.protectNTFS=false https://github.com/theMillenniumFalcon/better-auth.git
```

but now I don't have the file, and cannot create it either as it is prohibited on Windows. Any workaround for this?

**Comment by qamarq** [comment]
I think we can't do anything. I hope this will be fix asap cause I need to push some changes to fix errors.

**Comment by tklein1801** [comment]
@qamarq you can use an Github Codespace which won't have this issue (because they dont run on Windows and its file-system) and push the code

**Comment by Bekacru** [comment]
> Was able to clone the repository without including the `*auth.ts` file using following command:
> 
> ```
> git clone -c core.protectNTFS=false https://github.com/theMillenniumFalcon/better-auth.git
> ```
> 
> but now I don't have the file, and cannot create it either as it is prohibited on Windows. Any workaround for this?

It's cause of solid start catch all route symbol. I'll remove the file.

**Comment by Bekacru** [comment]
try it and let me know

**Comment by theMillenniumFalcon** [comment]
It works like charm. No further errors. Closing the issue for now.
