### ISSUE TITLE
VERIFY EMAIL BUG

### ISSUE THREAD

**Issue by olivebishop** [better-auth/better-auth#251]
#  Describe the bug
## A clear and concise description of what the bug is.
- When i signup using  full name , email and password and am taken to dashboard where there is a banner that says verify your email when i check my email i get verify link when i click on it i get 500 status

**Comment by Bekacru** [comment]
If this is happening on the demo, it could be related to `libsql` or Turso rather than Better Auth. If it's happening locally, please share the server logs so I can help.

**Comment by olivebishop** [comment]
Its on demo

**Comment by Bekacru** [comment]
please try it again and let me know if it's still an issue.

**Comment by nathanielrich** [comment]
i got the same error 
![image](https://github.com/user-attachments/assets/110e2b99-7316-407b-8f85-77e81105c2d6)

**Comment by nathanielrich** [comment]
> i got the same error 
> 
> ![image](https://github.com/user-attachments/assets/110e2b99-7316-407b-8f85-77e81105c2d6)
> 
> 


My error was an drizzle error:

https://github.com/drizzle-team/drizzle-orm/issues/1113#issuecomment-2290376956

**Comment by Bekacru** [comment]
I think this should be fixed past v1. Feel free to re-open if not.
