### ISSUE TITLE
Sign Up/Sign In with an Email OTP

### ISSUE THREAD

**Issue by sshrshnv** [better-auth/better-auth#252]
**Is your feature request related to a problem? Please describe.**

It is very inconvenient to sign up/ sign in using a magic link, because for example:
- Safari will open the link in an isolated window that does not have access to the application
- The link cannot be opened on the TV

**Describe the solution you'd like**

It is much more convenient to send a one-time code that the user can read from any device and enter into any device.

**Describe alternatives you've considered**

It would be possible to use the magic link plugin without url and I see a pull request with the ability to create custom code, but a callback/error redirect prevents it.

**Comment by luksch42** [comment]
Need that too. It was already mentioned in #93.

**Comment by Bekacru** [comment]
I'm gonna close this since it's a duplicate, hopefully we'll have this by Friday 🚀
