### ISSUE TITLE
Argument password is missing.

### ISSUE THREAD

**Issue by saidMounaim** [better-auth/better-auth#262]
After I set everything up, I tried to log in with email and password, but I got an error: 'Argument password is missing.' I checked the password in the console, and it looks fine. I'm using Prisma and Next.js

```
async function onSubmit(values: z.infer<typeof SignupFormSchema>) {
    const { name, email, password } = values;
    console.log(password);
    await authClient.signUp.email({
      email,
      password,
      name,
      image: "",
      fetchOptions: {
        onResponse: () => {
          setLoading(false);
        },
        onRequest: () => {
          setLoading(true);
        },
        onError: () => {
          alert("Something went wrong");
        },
      },
    });
  }
```

**Comment by GregorWedlich** [comment]
I think your code is correct. Which version are you using and please try to format the code correctly with Markdown in the future, e.g. with three “ ```ts ” backticks and three at the end.

**Comment by saidMounaim** [comment]
this is the version, 
`better-auth": "^0.5.2-beta.12"`

**Comment by GregorWedlich** [comment]
Sorry there seems to be something wrong with you, it works fine for me.

**Comment by Unyxos** [comment]
hey @saidMounaim i had the same issue yesterday, what does your Prisma schema looks like ? I had a dummy User schema with password field and it broke the whole thing as password isn't saved in the user but in account
