### ISSUE TITLE
Cannot find module better-auth/adapters/drizzle

### ISSUE THREAD

**Issue by claughinghouse** [better-auth/better-auth#266]
**Describe the bug**
When trying to use the `drizzleAdapter` I run into this typescript error: `cannot find module better-auth/adapters/drizzle`

**To Reproduce**

1. Install better-auth
2. import it into the file
3. Import the `drizzleAdapter` per [the docs](https://www.better-auth.com/docs/concepts/database#drizzle-adapter)
4. Error pops up

**Expected behavior**
No issue importing the module or types in typescript. 

**Screenshots**
<img width="1332" alt="Screenshot 2024-10-20 at 11 11 59 AM" src="https://github.com/user-attachments/assets/92da1b9a-f8f0-430e-8175-8730558e206b">

**Desktop (please complete the following information):**

- OS: macOS
- Browser: N/A
- Version: N/A - better-auth 0.5.2-beta.7

**Additional context**

**Comment by Bekacru** [comment]
can you confirm if this still an issue on latest version `0.5.2-beta.16`?

**Comment by claughinghouse** [comment]
> can you confirm if this still an issue on latest version `0.5.2-beta.16`?

At first pass looks like this is fixed in `0.5.2-beta.16`.
