### ISSUE TITLE
Support for Custom User Session Data

### ISSUE THREAD

**Issue by mamlzy** [better-auth/better-auth#278]
I would like to request support for adding custom user session data in `better-auth`, similar to the functionality offered by `next-auth`. This feature would allow developers to include additional user-specific information within the session object that is returned after a successful authentication.

The ability to customize session data is crucial for many use cases, such as storing roles, permissions, and other metadata directly within the session. This can simplify access to user-specific information throughout an application without the need for additional database queries or custom implementations.

It would be great if `better-auth` could provide a way to extend the session object either through a callback function or a similar mechanism, allowing for more flexibility in handling session data.

Thank you for your consideration, and I'm looking forward to any feedback or updates on this request!

**Additional context**
Example of extending the session from `auth.js`
![image](https://github.com/user-attachments/assets/51d5f7a7-7154-41f2-856f-22fbcfa716ac)

**Comment by nathanielrich** [comment]
pls add this feature, this is very important, cause so we can customize everything by our own...

**Comment by mikeyXmomo** [comment]
Maybe you can try this https://www.better-auth.com/docs/concepts/typescript#additional-fields

**Comment by nathanielrich** [comment]
> Maybe you can try this https://www.better-auth.com/docs/concepts/typescript#additional-fields

The issue is that this approach would add fields to the database. Instead, we need a callback function to fetch or query additional data for the session user object as needed.

**Comment by nathanielrich** [comment]
pls put this on the roadmap, this is an essential feature to customize the session-user for our individual needs.

**Comment by romainchkr** [comment]
I'm looking for something similar too. It would be great in order to enable Row Level Security in a Supabase backend. Do you know if there's any way to do it without that feature ??
