### ISSUE TITLE
Signing up with username documentation spelling mistake

### ISSUE THREAD

**Issue by kanesmall** [better-auth/better-auth#279]
This isn't technically a bug, so I apologise if this isn't the correct approach for pointing this out, I also couldn't see any mention to documentation in the contribution guidelines, but of course, more than happy to fork, branch and PR if it's allowed!

There's a small spelling mistake in the docs for the `signing up with username` plugin: https://www.better-auth.com/docs/plugins/username#signup-with-username

> To sign up a user with username, you can use the existing **singUp**.email function provided by the client.

`singUp` should be `signUp`

Let me know if I'm okay to amend :)

**Comment by Bekacru** [comment]
feel free to open a pr
