### ISSUE TITLE
Passkey plugin can't set on username or phoneNumber

### ISSUE THREAD

**Issue by amirhd-com** [better-auth/better-auth#287]
**Describe the bug**
the passkey plugin when add/generated, just use email, can't set username or phoneNumber for add/signIn when use passkey.

**Comment by Bekacru** [comment]
no plans to support manual passkey login with other identifiers

**Comment by amirhd-com** [comment]
> no plans to support manual passkey login with other identifiers

So it's really useful, any way to cook it?
