### ISSUE TITLE
Authentication error while signing in with username.

### ISSUE THREAD

**Issue by 0xPratikPatil** [better-auth/better-auth#293]
**Describe the bug**
I am using the username plugin and can sign up users properly. However, when signing in with a username, it gives the following error. Additionally, it does not return a proper error message in the toast notification; instead, it returns an empty error message.

**To Reproduce**
![Screenshot from 2024-10-22 23-04-15](https://github.com/user-attachments/assets/8d1f83d1-8947-4c5e-9182-ef2e7801270d)
![Screenshot from 2024-10-22 23-04-33](https://github.com/user-attachments/assets/b5030536-192e-41db-8b1a-10f07d7468cc)

**Expected behavior**
It must properly sign in the user with a username and password, then return a session cookie.

**Screenshots**
![loginithusername](https://github.com/user-attachments/assets/a1564ca2-eaa9-4176-a58d-3c90d0115e66)

**Additional context**
NextJs + Hono + Drizzle (Supabase) 
Browser:Brave
Os:Kali

**Comment by Bekacru** [comment]
Make sure you're using the latest version of Better Auth. `pnpm i better-auth@latest`

**Comment by 0xPratikPatil** [comment]
Yes, this issue is solved by installing the latest version.
I just wanted to take a moment to say thank you for creating and sharing this fantastic library! 🎉 It's clear that a lot of effort and thought went into making it, and it's going to be super helpful for projects like mine. The documentation is also well-organized.Keep up the great work, and I look forward to seeing this project grow! 🚀

**Comment by Bekacru** [comment]
oh thanks. Really appreciate that! ❤️
