### ISSUE TITLE
node-handler mounted incorrectly

### ISSUE THREAD

**Issue by tklein1801** [better-auth/better-auth#31]
The node handler throws a `HTTP 404` error message for POST requests because it is implemented as a GET endpoint in ExpressJS (as in the [documentation](https://www.better-auth.com/docs/integrations/node#mount-the-handler)).

```ts
...
app.get(‘/api/auth/*’, toNodeHandler(auth));
...
```

The quick and simple attempt to implement the whole thing using `app.use` failed because the client then always receives the `better-call` error message with the following content:

```
[better-call]: Make sure the URL has the basePath (/api/auth).
```

Translated with DeepL.com (free version)

I haven't quite figured out the logic with `better-call` yet, so I can't say exactly what a solution might look like.

**Comment by Bekacru** [comment]
you should use app.all instead

**Comment by tklein1801** [comment]
@Bekacru thank you. I wasn't aware that `app.all` exists
