### ISSUE TITLE
Github login zod error

### ISSUE THREAD

**Issue by koohz** [better-auth/better-auth#312]
**Describe the bug**
Trying to login with github provider give a "please_restart_the_process" error. Github portal have the redirect url pointing to:
**http://localhost:3000/api/auth/callback/github**
The other login providers works well.

![Screenshot 2024-10-23 193121](https://github.com/user-attachments/assets/a392d4c6-b281-44d0-aa6e-1314dde3ac88)

![Screenshot 2024-10-23 193114](https://github.com/user-attachments/assets/5a7c589c-9123-4e02-8a55-9ca172dab488)

**To Reproduce**

All steps described in better-auth docs

**Expected behavior**
Should login like as other social provider do

```typescript
import { authClient } from "@/lib/auth-client";

/*
* .....
*/

<Button
  variant="outline"
  className="w-full"
  onClick={() => {
    authClient.signIn.social({
      provider: "github",
    });
  }}
>Login with Github</Button>
``` 

```typescript
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { db } from "@/server/db";
import { env } from "@/env";


export const auth = betterAuth({
  emailAndPassword: {
    enabled: true,
  },
  socialProviders: {
    discord: {
      clientId: env.DISCORD_CLIENT_ID,
      clientSecret: env.DISCORD_CLIENT_SECRET,
    },
    github: {
      clientId: env.GITHUB_CLIENT_ID,
      clientSecret: env.GITHUB_CLIENT_SECRET,
    },
    google: {
      clientId: env.GOOGLE_CLIENT_ID,
      clientSecret: env.GOOGLE_CLIENT_SECRET,
    },
  },
  database: prismaAdapter(db, {
    provider: "postgresql", // or "mysql", "postgresql", ...etc
  }),
  logger : {
    disabled : false,
    verboseLogging : true
  }
});
```

**Comment by himself65** [comment]
how do you fix this?

**Comment by koohz** [comment]
Check all URL in your github OAuth application

**Comment by dvalbuena1** [comment]
For anyone using GitHub Apps instead of OAuth Apps. To fix it you need to add the "Email addresses" access under "Account permissions" section.
