### ISSUE TITLE
The plugins that returns the functions was broken

### ISSUE THREAD

**Issue by rachhen** [better-auth/better-auth#313]
**Describe the bug**
The functions of plugin that returns from `createAuthClient` can't use as a hook on the client. The typeof that hooks is an object not function. When I call hook and log it return `Promise` instead of data.

**To Reproduce**

1. Add plugin to the `createAuthClient` 
2. Go to component
3. Use the hooks 
4. Got error

**Expected behavior**
It should be use as hook and returns data instead of Promise and no Typescript error.

**Screenshots**
<img width="824" alt="image" src="https://github.com/user-attachments/assets/d978974d-8631-4ab6-b43e-077cb70210e7">

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Chrome
- Version 0.5.3-beta.17

**Additional context**

The client:
```ts
export const authClient = createAuthClient({
  fetchOptions: {
    onError(e) {
      if (e.error.status === 429) {
        toast.error("Too many requests. Please try again later.");
      }
    },
  },

  plugins: [
    adminClient(),
    organizationClient(),
    passkeyClient(),
    twoFactorClient({
      redirect: true,
      twoFactorPage: "/two-factor",
    }),
  ],
});
```

Component
```tsx
export function OrganizationDropdown() {
  const organizations = authClient.useListOrganizations();

  console.log(organizations)

return <div></div>
}
```

Typescript error:
```ts
This expression is not callable.
  Type 'PreinitializedWritableAtom<{ data: { id: string; name: string; slug: string; createdAt: Date; logo?: string | undefined; metadata?: any; }[] | null; error: BetterFetchError | null; isPending: boolean; isRefetching: boolean; }>' has no call signatures.
```
The log result:
```ts
Promise { <pending> }
```

**Comment by Bekacru** [comment]
make sure you import the client from "better-auth/react"

**Comment by rachhen** [comment]
It work thank you

**Comment by productdevbook** [comment]
vue problem

![CleanShot 2024-12-04 at 00 24 49@2x](https://github.com/user-attachments/assets/b123dbe2-4cdd-4f34-8b78-14085915308f)
