### ISSUE TITLE
New session endpoint not updated in client

### ISSUE THREAD

**Issue by darklight9811** [better-auth/better-auth#315]
**Describe the bug**
When the react client tries to fetch the endpoint for session, it goes for `/session` instead of `/get-session`

**To Reproduce**

1. setup everything
2. open the client and see it trying to get the session and it being returned a 404

**Expected behavior**
for the endpoint to reach, even if its not authenticated

**Additional context**
This was working on 0.5.2, so it must be a new bug, the endpoint for the backend is being described here:
https://github.com/better-auth/better-auth/blob/2f3ced95fb62ab9eaf7806beadfb86a3aff09087/packages/better-auth/src/api/routes/session.ts#L15

**Comment by Bekacru** [comment]
this should be fixed since `0.5.3-beta.2`
