### ISSUE TITLE
Blank app when installing better-auth

### ISSUE THREAD

**Issue by alvarofc** [better-auth/better-auth#319]
**Describe the bug**
When I install better-auth on a React + swc app all the content of the page disappears.

**To Reproduce**

1. Use `npm create cloudflare@latest -- my-react-app --framework=react` to create react app + swc
3. Install tailwind
4. Install better-auth
5. The boilerplate app becomes blank

**Expected behavior**
I would expect that nothing changes in the ui when installing better-auth

**Desktop (please complete the following information):**

- OS: Windows 11 
- Browser chrome
- Version 130.0.6723.60 

**Additional context**

**Comment by Bekacru** [comment]
Make sure you're using the latest version, and please provide more information than just a blank page. Check the console for any errors.

**Comment by alvarofc** [comment]
Using the @latest fixed it. Thank you!
