### ISSUE TITLE
Unable to generate Prisma schema for the database.

### ISSUE THREAD

**Issue by 0xPratikPatil** [better-auth/better-auth#323]
**Describe the bug**
Unable to generate Prisma schema for the database.

**To Reproduce**
```
import { PrismaClient } from "@prisma/client";
import { prismaAdapter } from "better-auth/adapters/prisma";

const prisma = new PrismaClient();

export const auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql",
  }),
```
Empty Schema nothing else
```
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```
**Commands Used** 
`bunx @better-auth/cli  generate
`
Even after running the command `bunx prisma generate`, it didn't work.

**Expected behavior**
It generates the Prisma schema according to the auth setup and creates appropriate tables/schemas.

**Screenshots**

<img width="1131" alt="Screenshot 2024-10-24 at 7 07 47 PM" src="https://github.com/user-attachments/assets/dfba35f2-f2f6-4ae4-89cf-753a4e90beb0">

**Additional context**
Version : ^0.5.4-beta.6

**Comment by Bekacru** [comment]
initiate the prisma client before you try to generate the schema

**Comment by 0xPratikPatil** [comment]
Yes, it worked. The catch is that I was running with an empty schema. First, I had to create a random schema to initialize it, then generate the real one.Thank You.

**Comment by 0xPratikPatil** [comment]
I don't know why, but when I shifted to Prisma + MongoDB, my signUp.username() stopped working. However, I can still use signUp.email() to register via username as the field is optional.

**Comment by Bekacru** [comment]
yeah it's moved to signUp.email since a couple of versions back
