### ISSUE TITLE
The username field is mandatory when creating a new user through the admin

### ISSUE THREAD

**Issue by 0xPratikPatil** [better-auth/better-auth#324]
If the developer uses the username field in the project, it must appear when creating a new user, along with email, password, name, and role.

Reference: client.admin.createUser()

**Comment by lanzclintonv** [comment]
I encountered the same issue and found a workaround using data.

```
await authClient.admin.createUser({
          name: "Admin for Testing",
          email: "admin@example.com",
          password: "password1234",
          role: "admin",
          data: {
            username: "admin",
          },
```

This is a sample on how you can append the username.

**Comment by 0xPratikPatil** [comment]
OK, thanks for providing the solution. This is great if the user schema has other data fields to manipulate.

**Comment by Bekacru** [comment]
No plans to infer types in the admin plugin. It’s a hacky workaround and heavy on ts server, passing data works well enough and is secure enough, as it can only be done by admins.
