### ISSUE TITLE
How to access user accounts?

### ISSUE THREAD

**Issue by zAlweNy26** [better-auth/better-auth#325]
I would like to use information from the `accounts` table that stores providers to perform some actions, but I haven't found a way to do this except within a custom plugin. Is it possible to do it from the outside? Am I missing something fundamental?

**Comment by koohz** [comment]
Maybe I'm misunderstanding the question but, couldn't you do this with your database client? 

```typescript
prismaClient.user.findFirst({
    where : {
        id : userID
    },
    include : {
        Account : true
    }
})
```

**Comment by zAlweNy26** [comment]
You are right, I just thought it would be a nice addition to have also that default table exposed from the betterAuth APIs. Or maybe it's unnecessary and I should do as you said...
