### ISSUE TITLE
In Demo version invited member cannot accept a invitation request.

### ISSUE THREAD

**Issue by hempun10** [better-auth/better-auth#326]
**Describe the bug**
In a demo version of better auth, if we invite a member and invitation link is send to mail but we we click  `Join Team` button it get redirects to vercel and vercel says you aren't a team member. I don't know its a bug or it is as it like 

<img width="1665" alt="Screenshot 2024-10-24 at 9 34 52 PM" src="https://github.com/user-attachments/assets/0f83741d-7f81-412f-9687-800839acf3a3">

**To Reproduce**

1. Go to [Demo Url](https://demo.better-auth.com/)
2. Create an account and Create new organization
3. Click to invite member, fill up the details
4. When you receive a mail click on` join team `
5. See error

**Expected behavior**
It should redirect to dashboard 

**Screenshots**
<img width="1665" alt="Screenshot 2024-10-24 at 9 34 52 PM" src="https://github.com/user-attachments/assets/0f83741d-7f81-412f-9687-800839acf3a3">

**Desktop (please complete the following information):**

- OS: MacOS Latest
- Browser : Brave
- Version : latest

**Additional context**
If it's as expected behaviour please mention me.

**Comment by Bekacru** [comment]
this is no longer the case
