### ISSUE TITLE
fix: two-factor unverified sessions shouldn't appear as active sessions

### ISSUE THREAD

**Issue by 0xPratikPatil** [better-auth/better-auth#348]
**Describe the bug**
I am using the same code for my project and was using version 0.5.4-beta.6. I just updated the package to 0.6.0 and changed the auth middleware throughout my code, and this is causing the error.

**Screenshots**
![Screenshot from 2024-10-26 23-50-36](https://github.com/user-attachments/assets/dbec54ba-f143-46ab-ac93-36c5549107ef)

**Comment by Bekacru** [comment]
the docs just got updated. you'll need to make a fetch call directly instead of using the authClient

https://www.better-auth.com/docs/integrations/next#middleware

**Comment by 0xPratikPatil** [comment]
The problem is solved now, thank you.

I have one question: 
For users using two-factor authentication, if someone enters the correct credentials but cannot bypass the 2FA, a session is generated by the login function but not returned to the user until they enter the correct code. During this time, we see the active session, but it's not in use since the threat actor failed to bypass 2FA. What happens to that session.It must be deleted after some time? otherwise, it will unnecessarily appear in active sessions until it expires. We can show that in the user's activity but not a active session

**Comment by 0xPratikPatil** [comment]
@Bekacru

**Comment by Bekacru** [comment]
Yeah valid concern. Maybe we should `isActive` property for session.

**Comment by 0xPratikPatil** [comment]
Yes, sir, I'm just pointing out the issue.
