### ISSUE TITLE
optimistic update

### ISSUE THREAD

**Issue by darklight9811** [better-auth/better-auth#349]
**Is your feature request related to a problem? Please describe.**
When you logout (using react), you wait for the request to finish to update the UI. It would be better for the user experience if we removed the cookies and already updated the ui.

**Describe the solution you'd like**
Don't wait for the logout request to the backend to happen, update the UI before that happens.

**Describe alternatives you've considered**
none

**Comment by luksch42** [comment]
While optimistic updates are excellent for non-critical actions, logging out is a security-sensitive event. Updating the UI before confirming the logout could lead to misunderstandings if the session isn't properly terminated on the server side. To ensure user security, imo it's best to update the UI only after the backend confirms the logout.

If you still need optimistic updates, you could implement that directly in your frontend.

**Comment by darklight9811** [comment]
@luksch42 how could I do that? the better-auth has the single source of truth for the user and session, are you talking about encapsulating that information so I can do this implementation through it?

**Comment by luksch42** [comment]
@darklight9811 #365 exposes the client store. You should be able to manipulate the data there. The PR has not been merged yet, but work on it is already in progress.

update: merged in [v0.6.3-beta.1](https://github.com/better-auth/better-auth/releases/tag/v0.6.3-beta.1) :)
