### ISSUE TITLE
Expo React Native Support

### ISSUE THREAD

**Issue by Jonatthu** [better-auth/better-auth#35]
If you already support JWT or some bearer token header this should work out of the box...

**Comment by qamarq** [comment]
It does. [check here](https://www.better-auth.com/docs/plugins/bearer)

**Comment by Jonatthu** [comment]
@qamarq Also there is some built in libraries at expo that support apple login for example, would be nice to explore and include it in the documentation https://docs.expo.dev/versions/latest/sdk/apple-authentication/
Better auth has potential to be universal :D

**Comment by Bekacru** [comment]
merged!
