### ISSUE TITLE
TRPC Support

### ISSUE THREAD

**Issue by Jonatthu** [better-auth/better-auth#36]
Just make a router handler that supports TRPC 10 and 11 versions

**Comment by Bekacru** [comment]
TRPC already supported. No plans to have any deeper integration.

Here is an example using trpc with t3 stack
https://github.com/Bekacru/ct3-better-auth

**Comment by alan345** [comment]
Another example with fastify tRPC and better Auth

https://github.com/alan345/Fullstack-SaaS-Boilerplate

**Comment by lucasriondel** [comment]
@alan345 thanks a lot. your setup helped me configure it properly even if I had to add fastify to my project.

@Bekacru It is definitely supported but I think the implementation could be better. Would that be possible to have better documentation and possibly helpers from better-auth to achieve the linking of better-auth with TRPC ?
