### ISSUE TITLE
LibsqlDialect doesn't work with encryptionKey option

### ISSUE THREAD

**Issue by MurkyTheMurloc** [better-auth/better-auth#364]
**Describe the bug**  
When using `better-auth` with `LibsqlDialect` and enabling the `encryptionKey` option, an `SQLITE_NOTADB` error occurs. Disabling the `encryptionKey` option resolves the issue, but this disables encryption, which may be necessary in some use cases.

**To Reproduce**  

1. Configure `better-auth` to use a SQLite database.
2. Set up `LibsqlDialect` with the following configuration:
   ```javascript
   const dialect = new LibsqlDialect({
       url: "file:./auth/auth.db",
       syncUrl: process.env.TURSO_DATABASE_URL,
       authToken: process.env.TURSO_AUTH_TOKEN,
       syncInterval: 60,
       encryptionKey: process.env.ENCRYPTION_KEY,  // Enable encryption key
   });
3. Attempt to call `auth.api.signUpEmail()`
4. See error:
   ```json
   {
     "code": "SQLITE_NOTADB",
     "rawCode": 26,
     "name": "LibsqlError"
   }

**Expected behavior**  
The database should be accessed without errors when `encryptionKey` is specified.

**Screenshots**  
N/A

**Desktop (please complete the following information):**

- OS: macOS
- Node.js version: 22.6.0
- better-auth version:  0.6.2
- SQLite version: latest

**Smartphone (please complete the following information):**  
N/A

**Additional context**  
The issue may relate to how `better-auth` interacts with SQLite encryption, or it may stem from a misconfiguration. Documentation or clarification on supported encryption setups would be helpful.

**Comment by MurkyTheMurloc** [comment]
```javascript
const auth = betterAuth({
  emailAndPassword: {
    enabled: true,
  },
  database: {
    dialect: dialect,
    type: "sqlite",
  },
  plugins: [
    admin(),
    organization({
      ac: ac,
      roles: {
        member,
      },
    }),
  ],
});```

**Comment by Bekacru** [comment]
We don’t have direct interaction with the underlying implementation of the LibSQL dialect for Kysely. I’m not sure if encryption requires a different configuration with Kysely, but if it does, feel free to open another issue mentioning that. But, this seems like a problem with the Kysely dialect itself rather than Better Auth. If the issue is due to misconfiguration on our end, feel free to open another issue.
