### ISSUE TITLE
Google auth is not working

### ISSUE THREAD

**Issue by himself65** [better-auth/better-auth#367]
**Describe the bug**

https://discord.com/channels/1288403910284935179/1300894488272699454

**To Reproduce**

Just use next.js example and setup google tokens, shows `No stored state found`.

**Expected behavior**

Should work

**Comment by LovelessCodes** [comment]
Google Auth **is** working as expected.

I've setup a project on a VPS, with a given domain.     
Using this project: [nextjs-better-auth](https://github.com/LovelessCodes/nextjs-better-auth)    
Link: [Google Auth NextJS Demo](https://auth.betterjs.dev/)

**Comment by himself65** [comment]
yeah it's working

**Comment by himself65** [comment]
I'm not sure why it was not working for me, maybe multiple plugins? I will keep open until I figure out

**Comment by himself65** [comment]
This seems like the issue when I have different domain for backend and frontend. like a.com for backend and b.com for frontend. 

The workaround is to set backend and frontend under the same domain, like auth.a.com and frontend.a.com
