### ISSUE TITLE
[Multisession cookie not persistent]

### ISSUE THREAD

**Issue by Kevinvincentals** [better-auth/better-auth#369]
**Describe the bug**
Multi-session does not work correctly as expected. The cookie is upon login is set correctly but removed quickly after. Tested in NextJS 15

**To Reproduce**
1. Do a fresh install of NextJS 15
2. Install better-auth and follow documentation to get auth flow working
3. Install the plugin for multi-session and enable it
4. Login and look in cookies

**Expected behavior**
It should set a cookie for each multi user thats logged in and keep it there

**Additional context**
Created a thread with another user in the discord. The user there also provided screenshots + a video showing the issue

**Comment by Bekacru** [comment]
It would be helpful if you could provide a reproducible project I can review. Just a thought—in case you're trying to sign out and then sign in to a different account, signing out might be clearing all session cookies, including multi-account cookies

**Comment by Kevinvincentals** [comment]
> It would be helpful if you could provide a reproducible project I can review. Just a thought—in case you're trying to sign out and then sign in to a different account, signing out might be clearing all session cookies, including multi-account cookies

Hello.
I have two options
1. I Can give you access to the current codebase running for my project where the issue happenfs
2. I just setup a fresh install / nextjs 15 with better Auth and it has same outcome, by simply following Docs:
Get started 
-> installation
-> basic usage 
Using mysql with Prisma

Only doing e-mail password combo 

About the cookie clearing- the multi cookie is not even being set upon login, so if it cleared when logging out - I dont Think thats an issue.

The multi cookie is set upon login and cleared in the same second

**Comment by AlfredoAlessandro** [comment]
https://github.com/user-attachments/assets/c8efb643-f733-4f83-b198-f9c97be564de

**Comment by AlfredoAlessandro** [comment]
I have the same problem, here I can show how my application looks like

https://github.com/user-attachments/assets/70e81932-0002-4593-bbf2-5768e57baec3

**Comment by Bekacru** [comment]
Hey guys, I was just taking a look at this today. I’m still unable to reproduce the issue, so if you could make a public repo for me to review, that would be great.

**Comment by Kevinvincentals** [comment]
> Hey guys, I was just taking a look at this today. I’m still unable to reproduce the issue, so if you could make a public repo for me to review, that would be great.

Hi Bekacru
Thank you for looking into this issue.

i will give this a try on my project again to see if the issue persists. Maybe a update has fixed it?
I'll let you know.

**Comment by Bekacru** [comment]
Hey guys this should be fixed starting from `0.8.5`

**Comment by Bekacru** [comment]
feel free to re-open if not
