### ISSUE TITLE
Phone plugin auto signUpOnVerification getTempEmail never works

### ISSUE THREAD

**Issue by kknd0** [better-auth/better-auth#381]
Phone plugin auto signUpOnVerification getTempEmail and getTempName never invokes , it actually never fires
https://github.com/better-auth/better-auth/blob/e528d5f91382b0e87f893497dd3fa999fe296b6b/packages/better-auth/src/plugins/phone-number/index.ts#L203
Always return temp-${phonenumber}

**Comment by AmineYagoub** [comment]
What version you use? It works fine for me
![Screenshot 2024-11-01 at 08 03 53](https://github.com/user-attachments/assets/2809107f-adee-4062-a8f3-78ac8af05649)
