### ISSUE TITLE
Feature: OneTime Confirm

### ISSUE THREAD

**Issue by nathanielrich** [better-auth/better-auth#393]
A feature that allows you to secure critical areas (e.g., deleting a user or similar actions - freely selectable). The user must, for instance, enter their password, or they receive an email with a one-time password (OTP) that they need to confirm. Once confirmed, the function is then triggered in the callback.

**Comment by AmineYagoub** [comment]
Yes actually this is what I'm looking for, @Bekacru any suggestion on how we can achieve this with passkey plugin?

**Comment by Bekacru** [comment]
I think this could be a plugin (or an internal plugin). Basically, the implementation should check if an endpoint requires a password or some kind of verification. It should hold the action state somewhere (maybe in a cookie) and, once verified, retrieve the action from the cookie and complete it.
