### ISSUE TITLE
Unable to Access Better Auth Documentation

### ISSUE THREAD

**Issue by BinarySenseiii** [better-auth/better-auth#411]
I am trying to access the Better Auth documentation at https://better-auth.com/ from Dubai, but I am unable to reach the homepage. It appears that the site is not loading, and I would like to know if it is restricted in certain countries or if there is another issue

**Steps to Reproduce:**

Open a web browser.
Navigate to https://better-auth.com/

_**Expected Result:**_ The homepage should load successfully, allowing access to the documentation.

**_Actual Result:_** The homepage does not load, and I receive a connection error.

**Additional Information:**

Location: Dubai, UAE
Device: Laptop, Ubuntu 24.04.1 LTS
Browser: Chrome n i even checked on all browsers

below is the screenshot
![webpage-not-accessible](https://github.com/user-attachments/assets/c8f47f97-d0b8-46a6-be95-4103d3527528)

**Comment by sankalpsingha** [comment]
I can confirm that I have the same issue. I had to use a VPN to access it. Its the entire UAE apparently. Currently trying to access it from Abu Dhabi.

**Comment by Bekacru** [comment]
this is due to a DNS issue. You can try to use a vpn or you could access the vercel domain instead `https://better-auth.vercel.app`
