### ISSUE TITLE
Email verification `redirectTo` is improperly composed 

### ISSUE THREAD

**Issue by svaraborut** [better-auth/better-auth#415]
**Describe the bug**
The `redirectTo` field of `authClient.forgetPassword({ ... redirectTo: '/auth/login' })` has an inconsistent behavior
with `callbackURL` within other methods. It is a perfectly resolvable relative URL, but it is not resolved properly by the
API. To the email this URL is sent
`http://localhost:4444/api/auth/reset-password/...?callbackURL=/auth/login` which upon visit redirects
me to `http://localhost:4444/api/auth/auth/login?token=J7pJqT6tmM6vWzg6vq427` which is wrong.

**Expected behavior**
The URL shall be resolved properly

**Comment by svaraborut** [comment]
I can solve this

**Comment by Bekacru** [comment]
> I can solve this

go for it
