### ISSUE TITLE
`autoSignIn` should extend to email verification and password reset

### ISSUE THREAD

**Issue by svaraborut** [better-auth/better-auth#416]
**Is your feature request related to a problem? Please describe.**
When the authentication flow has `requireEmailVerification`, the `autoSignIn` flag has no effect and disrupts the authentication flow.

**Describe the solution you'd like**
The `/auth/verify-email` endpoint shall also consider `autoSignIn` and authenticate the user implicitly. The same behavior shall be implemented in the password reset flow to `/auth/reset-password`.

**Comment by Bekacru** [comment]
we've added a flag for this use case `autoSignInAfterVerification` under `emailVerification`
