### ISSUE TITLE
Remove automated redirect for `forgetPassword`

### ISSUE THREAD

**Issue by svaraborut** [better-auth/better-auth#418]
**Describe the bug**
When calling `forgetPassword` the client automatically redirects to `callbackURL` breaking the authentication flow.

**Expected behavior**
The client shall not redirect as the `callbackURL` is forwarded to the user via email and is intended to be visited after the email link is clicked.

**Comment by Bekacru** [comment]
The `forgotPassword` method no longer has the `callbackURL` argument and doesn’t redirect anywhere unless done manually by the user.
