### ISSUE TITLE
Feature Request: Sign-in with Identity Token

### ISSUE THREAD

**Issue by oktaysenkan** [better-auth/better-auth#421]
**Is your feature request related to a problem? Please describe.**
I need to implement authentication with an OIDC ID token, but the current library doesn’t provide a direct method for this.

**Describe the solution you'd like**
I would like a method similar to `supabase.auth.signInWithIdToken` that allows signing in with an OIDC ID token.

**Additional context**
This example works with native login prompt.

```tsx
import * as AppleAuthentication from 'expo-apple-authentication';

const credential = await AppleAuthentication.signInAsync({
    requestedScopes: [
        AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
        AppleAuthentication.AppleAuthenticationScope.EMAIL,
    ],
});

console.log(credential.identityToken)
```

![image](https://github.com/user-attachments/assets/e8626b85-cd04-4e03-a80a-4c04db7d0e9a)

[Supabase Reference](https://supabase.com/docs/reference/javascript/auth-signinwithidtoken)

**Comment by abegehr** [comment]
This is great! Using the Apple identityToken, do we still have to set clientId and clientSecret on the apple provider? If so, when generating the apple clientSecret it needs to have an expiration date. Is it fine to use a super-long-lived token for clientSecret? https://developer.apple.com/documentation/accountorganizationaldatasharing/creating-a-client-secret

**Comment by abegehr** [comment]
Max. token lifetime that apple excepts seems to be 6 months: https://github.com/Faruqt/generate-apple-client-secret-key?tab=readme-ov-file#generate-apple-client-secret-key - therefore best-case would be to generate a clientSecret in the application itself from the p8-key.

**Comment by abegehr** [comment]
In case, we want to generate the apple client secret on-the-go in the future, here is a sample: https://github.com/WcaleNieWolny/capgo-social-login-backend-demo/blob/main/index.ts#L25

**Comment by abegehr** [comment]
I finally got "Sign-in with Apple" working on my iOS Capacitor app (should be the same for all hybrid platforms):

The main thing that tripped me up, is that better-auth requires `clientId` and `clientSecret` on `socialProviders.apple` in config -> this is where you're place the service id and jwt secret generated from p8-file for "Sign-in with Apple" on web.
However on native iOS, it doesn't use the service id but the app id (bundle id) as client id, so if using the service id as clientId in `signIn.social()` with `idToken`, it throws an error:  `JWTClaimValidationFailed: unexpected "aud" claim value`. 

For iOS native "SignIn with Apple" with idToken, it expects the app/bundle id as `clientId` and doesn't require the `clientSecret`.

**Comment by tlebeitsuk** [comment]
> I finally got "Sign-in with Apple" working on my iOS Capacitor app (should be the same for all hybrid platforms):
> 
> The main thing that tripped me up, is that better-auth requires `clientId` and `clientSecret` on `socialProviders.apple` in config -> this is where you're place the service id and jwt secret generated from p8-file for "Sign-in with Apple" on web. However on native iOS, it doesn't use the service id but the app id (bundle id) as client id, so if using the service id as clientId in `signIn.social()` with `idToken`, it throws an error: `JWTClaimValidationFailed: unexpected "aud" claim value`.
> 
> For iOS native "SignIn with Apple" with idToken, it expects the app/bundle id as `clientId` and doesn't require the `clientSecret`.

Thanks for the heads up! This should be added to the docs.

**Comment by irg1008** [comment]
I think the current implementation is wrong:

See: https://developer.apple.com/documentation/accountorganizationaldatasharing/creating-a-client-secret
* **aud**: use https://appleid.apple.com as the audience.
* **iss**: use the 10-character Team ID associated with your developer account

But right now in betetr-auth implementation we have:
```typescript
const { payload: jwtClaims } = await jwtVerify(token, publicKey, {
	algorithms: [jwtAlg],
	issuer: "https://appleid.apple.com",
	audience: options.clientId,
	maxTokenAge: "1h",
});
```

We are doind the reverse check and so when trying to log in we receive:

```log
code: 'ERR_JWT_CLAIM_VALIDATION_FAILED',
  claim: 'aud',
  reason: 'check_failed',
...
```
