### ISSUE TITLE
Enhance `definePayload` method in `jwt` plugin

### ISSUE THREAD

**Issue by svaraborut** [better-auth/better-auth#428]
**Is your feature request related to a problem? Please describe.**
When creating a JWT it may also be needed to embed session-related info (like `activeOrganizationId`).

**Describe the solution you'd like**
`definePayload` signature shall be `(user: User, session: Session) => Promise<...>`

**Comment by kziemski** [comment]
[line where we would pass the session?](https://github.com/better-auth/better-auth/blob/bf522217d7c00ce40ed49edbcd3131b977fb8f1f/packages/better-auth/src/plugins/jwt/index.ts#L233)
It actually looks like we would only need to pass the session that we reference the user from right?
