### ISSUE TITLE
Expose a `hasPassword` method on the client

### ISSUE THREAD

**Issue by svaraborut** [better-auth/better-auth#431]
**Is your feature request related to a problem? Please describe.**
Users do not know how to check if the user has a password set. Is my understanding that being the system multi-account the correct API  should be `authClient.listAccounts()` but is confusing for simple use cases.

**Describe the solution you'd like**
Provide a `hasPassword()` function on the client.

**Comment by Bekacru** [comment]
You can list the user accounts and find a provider with provider id `credential` that should be enough imo

**Comment by svaraborut** [comment]
I see users getting confused about it on Discord. Maybe a method provides a simple solution for newcommers imho.

**Comment by Bekacru** [comment]
I'm not seeing much confusion since we added `listAccounts`. If it keeps coming up, we'll add an FAQ section for it, but for now, I'm going to close this
