### ISSUE TITLE
Admin Plugin suggestions: stopImpersonating() and editUser()

### ISSUE THREAD

**Issue by lucaslevin** [better-auth/better-auth#435]
**Is your feature request related to a problem? Please describe.**

I think it would be a good idea to have admin.stopImpersonating() so admin don't have to logout of impersonated user (or wait for session to end). Also an admin.editUser() as a way of editing a users information.

**Describe the solution you'd like**

There is already the impersonatedBy (id) in the useSession(), so it could just be a switch back.

For user edit, it could just use a similar structure as the user.updateUser() but for Admins.

**Comment by Kevinvincentals** [comment]
What I did was save the admin  session in a cookie called admin_session
Then after impersonation - It switches around the session cookies and you are back.
Logic like this should be implemented. +1

**Comment by zawasp** [comment]
It seems "edit user" was not implemented @Bekacru
