### ISSUE TITLE
`auth.api.signOut()` missing types

### ISSUE THREAD

**Issue by taylorfsteele** [better-auth/better-auth#451]
**Describe the bug**
The `signOut` function via the api is missing types.

```
import { auth } from "~/lib/auth";

const someFunctionOnTheServer = async () => {
  const headers = getHeaders();

  await auth.api.signOut({ headers }) // No types
} 
```

**To Reproduce**

1. Create a [better-auth instance](https://www.better-auth.com/docs/installation#create-a-better-auth-instance)
2. Call `auth.api.signOut()`

**Expected behavior**
`api.signOut()` throws a type error without headers and provides types for the function

**Screenshots**
![image](https://github.com/user-attachments/assets/d36cbb4c-b283-49c1-aeaf-2dd7d221c491)

Other api functions types seem fine.

![image](https://github.com/user-attachments/assets/09a2a6c6-c399-4130-a801-7ee255668c68)

better-auth: 0.7.5-beta.5

**Comment by Bekacru** [comment]
merged and released on `0.7.5-beta.6`
