### ISSUE TITLE
Error with nanoid module

### ISSUE THREAD

**Issue by DenisOstr** [better-auth/better-auth#469]
**Describe the bug**
Error [ERR_REQUIRE_ESM]: require() of ES Module \node_modules\nanoid\index.js from \node_modules\better-auth\dist\index.cjs not supported. 
Instead change the require of index.js in \node_modules\better-auth\dist\index.cjs to a dynamic import() which is available in all CommonJS modules.

**To Reproduce**
This is my betterAuth initialization code. Upon further use, the server crashes and returns an error

```ts
import { betterAuth } from 'better-auth'
import { prismaAdapter } from 'better-auth/adapters/prisma'

import { prisma } from '@/config/database'

export const auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: 'postgresql',
  }),
})
```

**Additional context**
I use NodeJS with Express.

Here is my tsconfig.json:

```json
{
  "compilerOptions": {
    "target": "es2021",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "rootDir": "src",
    "outDir": "dist",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
}
```

**Comment by norjamille-kasan** [comment]
i encountered the same issue. any work around to this?
