### ISSUE TITLE
Nuxt worker init error

### ISSUE THREAD

**Issue by KazBrekker1** [better-auth/better-auth#478]
**Describe the bug**
Adding the auth handler in the /api/auth/[...all].ts breaks the app with the following worker.

**To Reproduce**
1. Setup nuxt with better-auth using postgres.
2. Using bun as the package manager.

**Screenshots**
<img width="845" alt="image" src="https://github.com/user-attachments/assets/f582c883-c237-4249-a5c2-5ea666fe354a">

**Desktop (please complete the following information):**

- OS: MacOs Sequoia
- Browser Chrome & Brave

**Additional context**
As soon as I comment out the auth.handler line in the Endpoint, the dev run/build finishes correctly

**Comment by Limerio** [comment]
Have you try to follow the recommended approach? https://www.better-auth.com/docs/integrations/nuxt

**Comment by KazBrekker1** [comment]
I tried the recommended approach with /server/api/[...auth].ts as well as the way the nuxt example does it, /server/api/auth/[...all].ts

both produce the same error.

Here is a stackblitz: https://stackblitz.com/~/github.com/KazBrekker1/nuxt-better-auth

**Comment by KazBrekker1** [comment]
with the release of v1.0, any news regarding the nuxt integration?
please let me know if im doing something wrong in the repo i linked previously

**Comment by KazBrekker1** [comment]
The issue was how i imported the pg Pool
It was:
`import { Pool } from "pg";`
it should be:
```
import pkg from "pg";
const { Pool } =pkg
```
