### ISSUE TITLE
When i use auth.api.** on serverside inside nextjs api route it require headers can we use api functions without session?

### ISSUE THREAD

**Issue by qasimali09** [better-auth/better-auth#497]

**Comment by firstaxel** [comment]
You can't use the API without the session cause it is need to get the cookie and the active state of the user currently logged in.

**Comment by Bekacru** [comment]
be specific which function exactly you think shouldn't require headers. some actions may still need headers to check for a session, depending on the use case. If you think an action is incorrectly requiring headers, please open a new issue and describe it properly so we can take a closer look.
