### ISSUE TITLE
Support for non sql databases

### ISSUE THREAD

**Issue by Bekacru** [better-auth/better-auth#5]
Just opening this issue to gauge interest in supporting non-SQL databases. If you're interested, give this issue a thumbs-up emoji "👍"

**Comment by shareef945** [comment]
there is definitely a lot of interest for non-SQL! thats the only thing holding me back from migrating from next-auth. (i hate it there lol)

**Comment by peckjon** [comment]
+1 for Redis and for MongoDB

**Comment by simonbengtsson** [comment]
Cloudflare kv and firestore would be cool!

**Comment by qamarq** [comment]
+1 for mongo

**Comment by Bekacru** [comment]
implemented 🎉
https://github.com/better-auth/better-auth/pull/29
