### ISSUE TITLE
405 when reaching /api/auth/... when hosted on vercel. Work locally

### ISSUE THREAD

**Issue by romainchkr** [better-auth/better-auth#510]
**Describe the bug**
I set up better-auth in a nextjs project. Everything work locally. However as soon as its hosted on vercel each time i call signIn or any auth method from the better auth client it return a 405 (Method not allowed) response.
Each time the /api/auth/x is called it return a 405.

The baseUrl is well set in the environment variables as well as the secret.

i'm turning my head around trying to fix it. Have you ever seen that ?

**Expected behavior**
The auth methods client side works

**Comment by romainchkr** [comment]
Everything works perfectlty when hosting elswhere like netlify. I have no clue why vercel is always giving me a 405 (Method not allowed) when trying an endpoint of the better-auth server.

**Comment by bleevv** [comment]
Hi, I encountered the same issue and resolved it through the following solution. You just need to add the code below to your next.config.ts:
```javascript
webpack: (config) => {
    config.externals.push({
      'utf-8-validate': 'commonjs utf-8-validate',
      bufferutil: 'commonjs bufferutil',
    })
    return config
  },
```

**Comment by romainchkr** [comment]
Hi !
Unfortunately it doesn't solve the problem on my side :(
Did you manage to debug/log some infos on the vercel side calling signin method and reaching endpoint /api/auth/x ? Because i don't even have logs on vercel side when calling better auth signin (i just got the error in the network tab/console tab of the browser). 
However my other api routes works perfectly and show logs

And ofc everything works fine hosting somewhere else 🥲
