### ISSUE TITLE
Failed to get session cookie on server side.

### ISSUE THREAD

**Issue by 0xPratikPatil** [better-auth/better-auth#511]
**Describe the bug**
Actually, I have two projects that use the same stack as Hono and TanStack, and of course, Better Auth. The issue is that when I copied my auth files to another project, which also has the same .env, I was unable to get a session on the newer project. After debugging, I discovered that when I pass headers to getSession(), there is no Better Auth cookie present.

**To Reproduce**
```
import { Hono } from "hono"
import { handle } from "hono/vercel"
import { auth } from "@/lib/auth/auth";
import { Session } from "@/types/auth";
import fileRoutes from "@/features/files/server/route";

const app = new Hono<{
    Variables: {
        user: Session["user"] | null;
        session: Session["session"] | null
    }
}>().basePath("/api");

app.use("*", async (c, next) => {
    const session = await auth.api.getSession({ headers: c.req.raw.headers });
    console.log(c.req.raw.headers)  //no better auth cookie
    if (!session) {
        c.set("user", null);
        c.set("session", null);
        return next();
    }

    c.set("user", session.user);
    c.set("session", session.session);
    return next();
});


app.on(["POST", "GET"], "/auth/**", (c) => {
    return auth.handler(c.req.raw);
});

const routes = app.route("/file", fileRoutes);



export const GET = handle(app)
export const POST = handle(app)

export type AppType = typeof routes

```
@Bekacru

**Comment by 0xPratikPatil** [comment]
After more debugging, I discovered they show cookies on auth routes but not on my custom routes.

**Comment by GeorgeCht** [comment]
I'm having the same error using hono in cf workers.

`const session = await auth.api.getSession({ headers: c.req.raw.headers });`

Session returns null so it probably doesn't get the cookies on my custom routes.

Also, can see the cookie or the auth bearer token when I log the raw headers.

@0xPratikPatil did you find out any solutions to this?

**Comment by 0xPratikPatil** [comment]
Yes, I tried the same thing with different Hono versions and TanStack components. I also attempted to change the auth configurations, but it's still not working. By the way, I am facing this issue with the 0.7.5 better auth version. I have the exact same code in another project, and it's working there, but not in the newer one.

**Comment by Bekacru** [comment]
make sure both of you are passing "credential": "include" on your fetch requests

**Comment by 0xPratikPatil** [comment]
Where exactly? @Bekacru

**Comment by Bekacru** [comment]
on the client where you're sending the request from

**Comment by 0xPratikPatil** [comment]
Is this new implementation necessary? It works fine on my other projects without doing this on better-auth 0.7.5 and previous versions.

**Comment by 0xPratikPatil** [comment]
```
import { auth } from "@/lib/auth/auth";
import { headers } from "next/headers";

export const getSession = async () => {
  const [session] = await Promise.all([
    auth.api.getSession({
      headers: await headers(),
    }),
  ]).catch((e) => {
    throw e;
  });

  return session;
};


```

**Comment by GeorgeCht** [comment]
Turns out in my case it wasn't passing the cookies correctly because I was using Hono's RPC client where you do something like this:
```
const client = hc<AppType>('http://localhost:8787/')
const res = await client.posts.$get()
```

Which basically is using a function similar to fetch under the hood, but I could not pass "credential": "include" in the requests.

So I had to basically write a custom fetch function like so:

```
export const client = hc<AppType>('http://localhost:8787/', {
  fetch: (input: RequestInfo | URL, requestInit?: RequestInit) => {
    return fetch(input, {
      method: requestInit?.method ?? 'GET',
      credentials: 'include',
      headers: {
        ...requestInit?.headers,
      },
      body: requestInit?.body ?? null,
    })
  },
})
```

IMHO it's an edge case, but if anyone is using Hono RPC with BetterAuth, this could help.

**Comment by 0xPratikPatil** [comment]
Me using the same in mine like this 
```
import { hc } from "hono/client"
import { AppType } from "../app/api/[[...route]]/route"

export const client = hc<AppType>(process.env.NEXT_PUBLIC_APP_URL!)
```

**Comment by 0xPratikPatil** [comment]
Thanks for the solution. However, it's not working for me. I think there might be something wrong with my project still don’t know how it is working in other projects fine.

**Comment by 0xPratikPatil** [comment]
@Bekacru  Can you help? None of these things are working for me.

**Comment by kareem717** [comment]
@0xPratikPatil Did you fix this?

**Comment by 0xPratikPatil** [comment]
Yes I have fixed it used same pkgs and version then it was working for me then

**Comment by mateussmohamed** [comment]
I had an issue getting the session on the server side with TanStack Start/Router API, and I solved it by adding headers to `authClient.getSession`

```typescript

import { getHeaders } from '@tanstack/react-start/server';


const fetchSession = createServerFn({ method: 'GET' }).handler(async (ctx) => {
  const session = await authClient.getSession({
    fetchOptions: {
      headers: new Headers(getHeaders())
    }
  });

  if (!session) {
    return {};
  }

  return session.data;
});

or

export const Route = createRootRouteWithContext<MyRouterContext>()({
  beforeLoad: async () => {
    const { data } = await authClient.getSession({
      fetchOptions: {
        headers: new Headers(getHeaders())
      }
    });
    return data;
  }
})


```
