### ISSUE TITLE
phone number + password login mechanism 

### ISSUE THREAD

**Issue by oYwyh** [better-auth/better-auth#530]
since the phone number plugin login the user by default on verification i don't see a reason why the mechanism isn't there yet
and if not planned for the soon future i think removing "allowing users to sign in" from the docs would be better, since i spent a good amount of time implementing the phone number functionality thinking that i will be able to sign users in using it just to get surprised that i can't lol

**Comment by Bekacru** [comment]
well that shouldn't be the case. you can try it on `0.8.4-beta.1`. Will be merged soon!

```ts
await authClient.signIn.phoneNumber({
    phoneNumber: "+123456789",
    password: "password",
    remeberMe: true //optional defaults to true
})
```
