### ISSUE TITLE
phoneNumber.verify() doesnt set phoneNumberVerified to true ?

### ISSUE THREAD

**Issue by oYwyh** [better-auth/better-auth#532]
so iam calling the `phoneNumber.verify()` function in my app, and when checking the database i see that the `phoneNumberVerified` column is still `FALSE` beside the OTP code being correct
```tsx
  await phoneNumber.verify({
      phoneNumber: value,
      code: data.otp
  })
```
- OS: Arch Linux
- Browser: Firefox
- Version: ^0.8.2

**Comment by Bekacru** [comment]
does the API return a success message?

**Comment by ywyher** [comment]
not currently on my device
but in my `auth.ts` file i made the `signUpOnVerification` option to be true
and on verifying the code it did create a user in the database
so i guess it did return a success message

**Comment by Bekacru** [comment]
I'm asking if error is returned here

```ts
const { data. error } = await phoneNumber.verify({
      phoneNumber: value,
      code: data.otp
  })
```
