### ISSUE TITLE
Plugin: Device cookie

### ISSUE THREAD

**Issue by hurby24** [better-auth/better-auth#54]
Plugin for device cookie implementation to deal with attacks along side with rate limiter.

Link: https://owasp.org/www-community/Slow_Down_Online_Guessing_Attacks_with_Device_Cookies

**Comment by Bekacru** [comment]
thanks for the suggestion but we have no plans to implement this currently
random password guessing attacks are unlikely to succeed, we already have rate limiting, people mostly have strong password practices, and other defenses like CAPTCHAs works much better. Plus, bots can easily clear cookies, so this wouldn't add much value.

I'm going to close this issue for now, but let us know if you have any other thoughts
