### ISSUE TITLE
Resend OTP code doesn't work

### ISSUE THREAD

**Issue by oYwyh** [better-auth/better-auth#541]
when a user register i send an email containing the OTP required to verify his email using :
```tsx
  await emailOtp.verifyEmail({
      email: email,
      otp: otp
  })
```
it does work successfully as expected, the issue is if the user doesn't receive the email
for this case i added a button that send the OTP again using 
```tsx
  await emailOtp.sendVerificationOtp({
      email: email,
      type: "email-verification",
  }
```
the function does add a record on the verification table **without deleting the previous OTP code record**, but when the user receive his new OTP code and try to verify the email with it, it throws invalid OTP, when i try the old OTP code it works
btw if i manually remove the previous OTP code record from the database, the new code works normally
is there a way to solve this ?

i was gonna try to delete the previous OTP code record from the database programmatically but there is no field in the verification table that i can use to indicate which OTP code belongs to which user

- OS: arch linux
- Browser: firefox
- Version: better-auth "0.8.3"

**Comment by Bekacru** [comment]
this should be fixed. Feel free to re-open if this is still an issue.
