### ISSUE TITLE
Google one-tap client: cannot get it to work

### ISSUE THREAD

**Issue by MrKepzie** [better-auth/better-auth#546]
Getting the following client-side issue:

` Parameter approval_state is not set correctly.`

My code is pretty simple:

```
 const authClient = createAuthClient({
      baseURL: baseURL,
      plugins: [
        oneTapClient({
            clientId: '...'
        })
      ],
    });
    authClient.oneTap({
      callbackURL: "/"
    });
```
Any idea how to fix?

**Comment by Bekacru** [comment]
https://stackoverflow.com/questions/78858622/approval-state-is-not-set-when-trying-to-add-google-login check this
