### ISSUE TITLE
Allow custom OAuth provider IDs in trusted providers

### ISSUE THREAD

**Issue by awesomepandapig** [better-auth/better-auth#559]
I am trying to use the [Generic OAuth](https://www.better-auth.com/docs/plugins/generic-oauth) plugin to provide one-click SSO for my application. Currently, however, I am unable to complete the flow. I can successfully authorize the application and this is what is logged by my SSO provider.

![Screenshot 2024-11-16 113808](https://github.com/user-attachments/assets/6ba73914-12b9-4267-9413-51b564d3a3a1)

Once it authorizes and connects to the callback, it does not sign me in and instead gives me the following error:

![image](https://github.com/user-attachments/assets/c5972891-9ae3-4793-9c16-8461695632ce)

I assume this is due to the the fact that the Generic OAuth provider is not linked with my account and that this is why the authorization is invalid.

**(Note: I would really appreciate if the verbose logging option provided explicit error messages that indicate WHY the authorizations are invalid for debugging purposes as currently I am left to guessing/reading the source code)**

Currently, BetterAuth does not support custom provider ID's for trusted providers:

```Type '"authentik"' is not assignable to type '"github" | "apple" | "discord" | "facebook" | "microsoft" | "google" | "spotify" | "twitch" | "twitter" | "dropbox" | "linkedin" | "gitlab" | "email-password"'.```

I believe that this is an oversight and that those using the Generic OAuth plugin should be able to setup these providers for account linking.

**Comment by Bekacru** [comment]
Hey, sorry for getting back to you late. It seems like the issue is failing during verification rather than linking. The error is returned directly from the provider, not from Better Auth. Check if your client ID and client secret are properly configured, and ensure you’ve provided a valid scope.
