### ISSUE TITLE
useSession not working properly

### ISSUE THREAD

**Issue by ayushsharma82** [better-auth/better-auth#569]
**Describe the bug**
I'm using `useSession` hook of better-auth in my nextjs project and it's not working properly in sense that - sometimes the `isPending` property is left as `true` and never switches to `false` once get-session request is completed.

I think this is the most critical part of the app, I'm using useSession to protect routes, show loader and do other things. With this current bug, my loader keeps spinning and the user is stuck forever at that loading animation.

**To Reproduce**

1. Sign in with email and password auth
2. Signout via `authClient.signOut();`
3. Refresh page
4. The `useSession` hook should break at this step and `isPending` variable would be stuck at `true`.

In the network monitor, I can see better-auth client SDK make the request to my backend and the response was received as well. But the client SDK fails to update the `isPending`, `data` and `error` fields.

**Expected behavior**
The `useSession` hook should never miss these `get-session` API responses or be stuck at `isPending` = `true` forever.

**Desktop (please complete the following information):**

- OS: macOS 15.1
- Browser: Safari
- Better-Auth Version: 0.8.4

**Comment by ayushsharma82** [comment]
More observation: It breaks 60% of the time after signout and works 40% of the time with `isPending` set to `false` shortly after receiving response from API.

**Comment by ayushsharma82** [comment]
Another great observation: This bug happens on Safari so far. I've tested with Chrome and the client SDK behaves properly in that case every single time.

**Comment by Bekacru** [comment]
As you can see [here](https://github.com/better-auth/better-auth/blob/main/packages/better-auth/src/client/query.ts#L46-L74), the `pending` value should reset on success or error. Could you verify if the request resolves properly or hangs on the response? Also, please update it to version 0.8.6 to make sure everything is up-to-date.

**Comment by ayushsharma82** [comment]
@Bekacru  I see but still the same thing. Something breaks in Safari, I checked network analyzer and XHR request is receiving valid response (200, null response, same as Chrome).

PS: Tried with `0.8.8-beta.2`

**Comment by ayushsharma82** [comment]
Solved. It was an issue within my own component.

**Comment by ruaanetwork** [comment]
> Solved. It was an issue within my own component.

can you please share what was the issue because i am having the same issue.
using react typescript vite project

**Comment by joseph-9900** [comment]
> Solved. It was an issue within my own component.

Hey @ayushsharma82  I am facing the same issue, can you please explain how did you solve?
