### ISSUE TITLE
Error when updating account password with adapter prisma

### ISSUE THREAD

**Issue by davidroulier** [better-auth/better-auth#581]
**Describe the bug**
When calling the resetPassword method from the authClient (react client) and using the Prisma adapter, I've an error saying the `id` field is missing from the where clause.

**To Reproduce**

My auth config :
```
database: prismaAdapter(db, { provider: "postgresql" }),
```
Using the `better-auth/react` client

```
const { error: err } = await authClient.resetPassword({ newPassword });
```

**Other infos**
Node version : `20.11`
Better-auth version : `0.8.6-beta.3`

**Screenshots**
![Capture d’écran 2024-11-18 à 13 18 30](https://github.com/user-attachments/assets/a1a89b3e-ee05-47d4-b14b-e1ba3d22b858)

**Comment by Bekacru** [comment]
should be fixed on `0.8.7-beta.1`
