### ISSUE TITLE
Session does not refresh everytime when `updateAge` is explicitly set to 0

### ISSUE THREAD

**Issue by Sebbev** [better-auth/better-auth#604]
**Describe the bug**
The `updateAge` option on the session options does not correctly handle 0 as a valid value, defaulting to the fallback value instead.

As describe in the type description it should allow for a 0 value to refresh every time it is used.

https://github.com/better-auth/better-auth/blob/a50fce1561137b0ac506eb88a29e8604cd72c454/packages/better-auth/src/types/options.ts#L293-L299

**To Reproduce**

1. Set `updateAge` to `0` in auth session options.
2. Use the session in any way.
3. `expiresAt` is not updated in DB.

**Expected behavior**
Update the `expiresAt` in the database whenever accessing the session.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Chrome
- Version 131.0.6778.85

**Additional context**
Could probably be fixed by just changing `||` to `??` on this line:
https://github.com/better-auth/better-auth/blob/a50fce1561137b0ac506eb88a29e8604cd72c454/packages/better-auth/src/init.ts#L87

There might also be more similar issues elsewhere.

**Comment by Bekacru** [comment]
fixed on `v1.0.0-canary.8`

**Comment by Bekacru** [comment]
feel free to re-open if not
