### ISSUE TITLE
npm list @better-auth/core

### ISSUE THREAD

**Issue by Blastecuk** [better-auth/better-auth#61]
Anyone else having issues installing on local using Next js?

**Comment by Bekacru** [comment]
what is the problem you're facing?

**Comment by Bekacru** [comment]
also there is no @better-auth/core. the package name is just "better-auth"

**Comment by Blastecuk** [comment]
> also there is no @better-auth/core. the package name is just "better-auth"

Sorry typo on my part should not let V0 get involved all sorted  🤣
