### ISSUE TITLE
Internal server error in Demo Showcase application 

### ISSUE THREAD

**Issue by hempun10** [better-auth/better-auth#628]
**Describe the bug**
There is an internal server while trying the demo version of better auth. `500`

**To Reproduce**
1.**Visit the URL:** https://demo.better-auth.com/sign-in
2.** Attempt to use any authentication service.**
3.**No toast messages will be displayed in response to a 500 error.**
4.**Open the network tab to view the internal server error.**

**Screenshots**
<img width="1660" alt="Screenshot 2024-11-23 at 3 11 39 PM" src="https://github.com/user-attachments/assets/781a412b-eb5a-41ec-97fa-6e912b2f5240">

**Desktop (please complete the following information):**

- OS: macOS Sequioa - v15.1
- Browser [Brave]
- Version [v1.70]

**Comment by Bekacru** [comment]
It should be back!
