### ISSUE TITLE
Migration failed on existing database

### ISSUE THREAD

**Issue by MrKepzie** [better-auth/better-auth#629]
Running cli migrate fails on existing database because the fields are required but unset on existing accounts.
I understand that this is in beta, but shouldn't any added extra field be `required=false` ?
How am I supposed to go around this on my end ?

```
npx @better-auth/cli@latest migrate -y
(node:8687) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ  🔑 The migration will affect the following:                                                                                                                                            Better Auth
-> token, createdAt, updatedAt fields on session table.
-> accessTokenExpiresAt, refreshTokenExpiresAt, scope, createdAt, updatedAt fields on account table.
-> updatedAt fields on verification table.
⠋ migrating...node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

error: column "createdAt" of relation "account" contains null values

```

**Comment by Bekacru** [comment]
If you are already using it in production, you should add the fields manually instead.

**Comment by MrKepzie** [comment]
Could it be that the migrate tool prints the type of the fields that would be added aswell as their name ?

**Comment by Bekacru** [comment]
Yeah, it might not be a bad idea to show what fields need to be added, prior to migration, even if it fails. But for now, you can check the schema in the docs.https://www.better-auth.com/docs/concepts/database#core-schema

**Comment by MrKepzie** [comment]
ok thanks, as long as it's up to date it's fine!
