### ISSUE TITLE
Mobile navbar menu scroll broken on website

### ISSUE THREAD

**Issue by w1png** [better-auth/better-auth#64]
https://github.com/user-attachments/assets/d9df4a9e-74ab-4707-8e30-2e8190df1854

**Comment by Bekacru** [comment]
@Kinfe123

**Comment by Kinfe123** [comment]
Will fix ASAP!

**Comment by Kinfe123** [comment]
Will fix that ASAP.

**Comment by Masood-ul-Rehman** [comment]
Hello @Bekacru I have forked the repo and fixed this issue you can see the pull request here https://github.com/better-auth/better-auth/pull/90     
Working video
https://github.com/user-attachments/assets/ad878c49-44e4-4739-92b2-740d02ee965a
