### ISSUE TITLE
Better Auth works on localhost but NOT production server

### ISSUE THREAD

**Issue by trunglehuynh** [better-auth/better-auth#642]
**Describe the bug**
I tested Better-Auth on local dev(http://localhost:3000/), it is working fine but the production version (host in vercel.com) does not work, all GET and POST https://<www.mydomain.com>/api/auth/get-session requests return 404.

**To Reproduce**
Request GET and POST https://<www.mydomain.com>/api/auth/get-session and get return 404

**Expected behavior**
Those requests should return 200 as localhost:3000

**Screenshots**
n/a
**Desktop (please complete the following information):**
Google Chrome
 
Tried:
 -I tested the production database, and It is working fine.
 -update provider client_id and client_secret.

**Comment by anatoliy-t7** [comment]
Did you solve it?

**Comment by trunglehuynh** [comment]
yes, it was an env mistake, I set **URL=https://<mydomain.com>/** , but it should be **URL=https://<mydomain.com>** without slash

**Comment by anatoliy-t7** [comment]
Thank for reply, but it does not work for me :(
