### ISSUE TITLE
Getting 404 for all API endpoints - SvelteKit

### ISSUE THREAD

**Issue by anatoliy-t7** [better-auth/better-auth#656]
Getting 404 Error for all API endpoints on a server - SvelteKit 
        
``` js
POST https://mydomain.com/api/auth/sign-in/email?currentURL=https%3A%2F%mydomain.com%2Fauth%2Flogin 404 (Not Found)
POST https://mydomain.com/api/auth/sign-up/email?currentURL=https%3A%2F%mydomain.com%2Fauth%2Fregister 404 (Not Found)
```

It is working `localhost`, but not on a server.
I set up `baseURL: PUBLIC_DOMAIN,`  for a server and a client instance.

**Desktop**
- OS: Mac OS latest
- Browser chrome
- Version latest

- better-auth 1.0.3
- SvelteKit (Svelte 5)
- I do not use SSR

**Comment by Bekacru** [comment]
make sure to mount the handler properly on your server. And you can check `/api/auth/ok` to check if the server is properly running.

**Comment by anatoliy-t7** [comment]
Currently: 
```js
const response = await svelteKitHandler({ event, resolve, auth });
response.headers.append('Access-Control-Allow-Origin', PUBLIC_DOMAIN);
return response;
```
and I tried
```js
return svelteKitHandler({ event, resolve, auth });
```

```js
export const auth = betterAuth({
	appName: PUBLIC_APP_NAME,
	baseURL: PUBLIC_DOMAIN,
	secret: BETTER_AUTH_SECRET,
	database: prismaAdapter(db, {
		provider: 'postgresql'
	}),
	emailAndPassword: {
		enabled: true,
		requireEmailVerification: false,
		minPasswordLength: 8,
		autoSignIn: true,
	},
})
```

**Comment by Bekacru** [comment]
can't tell much from here, but if 404 is returned that means the handler isn't properly mounted in `hooks.server.ts`. Make sure to follow the guide in the docs or the sveltekit example in this repo.

**Comment by anatoliy-t7** [comment]
I figured it out.

env was not set via: 
```
import { PUBLIC_DOMAIN } from '$env/static/private';

baseURL:  PUBLIC_DOMAIN
baseURL:  process.env.PUBLIC_DOMAIN
baseURL:  import.meta.env.PUBLIC_DOMAIN
```

Works only:
```
import { env } from '$env/dynamic/private';
baseURL:  env.PUBLIC_DOMAIN
```
