### ISSUE TITLE
createAuthClient().signIn.email({...}) does not call onError() in case of a fetch failure

### ISSUE THREAD

**Issue by bfovez** [better-auth/better-auth#657]
**Describe the bug**
`createAuthClient().signIn.email({...},{onError:...})` does not call `onError()` in case of a fetch failure.

**To Reproduce**

1. Create a client Auth on an API that makes the fetch fail on purpose:
```ts
// http://localhost:5174 makes the fetch fail on purpose
const auth = createAuthClient({ baseURL: 'http://localhost:5174' }) 
```

2. Call signIn:
```ts
await auth.signIn.email(
	{ email, password },
	{
		onError: (ctx) => {
			console.error('signIn error ' + ctx.error.message)
		}
	}
)
```

3. A "Failed to fetch" error is thrown, and `onError` is never called. We have to try / catch the whole thing and call the same code that lies within `onError` manually. 

**Expected behavior**
`auth.signIn.email` an other auth methods should catch any exception and call the `onError` callback accordingly, for better DX.

**Screenshots**

**Desktop (please complete the following information):**

OS: Windows 11
Browser: Chrome
Version: Node 21

**Comment by Bekacru** [comment]
This is expected behavior. The client only catches API returned errors not unexpected ones like `fetch failed`.
