### ISSUE TITLE
NeonDbError syntax error at or near "asc" (no order by field passed)

### ISSUE THREAD

**Issue by benjamindell** [better-auth/better-auth#660]
**Describe the bug**
I've migrated over from next-auth to better-auth but i'm hitting an issue. When i try and login, i get the error below:

ERROR   NeonDbError syntax error at or near "asc"

If I output the DB log, it looks like the issue is caused by there being no order by field being passed to the SQL

I am using the Drizzle adapter. The only overrides i've had to do is set the modelName for each table as they were named differently in my DB.

___QUERY___
select "userId", "type", "provider", "providerAccountId", "refresh_token", "access_token", "expires_at", "token_type", "scope", "id_token", "session_state", "crea
tedAt", "updatedAt" from "Account" where "Account"."userId" = $1 order by  asc limit $2
[ 'clw0gmvy50000j6kgi4vw9emu', 100 ]
___END_QUERY___

I've had a look through the source code but I cant seem to find where the sortBy field is passed. Does anyone have any clues?

**Comment by Bekacru** [comment]
could you confirm me, if this is still an issue on latest?

**Comment by benjamindell** [comment]
Amazing! Thanks for the quick reply. I've just updated the package to the latest version and that seems to have fixed it.

Thanks.
