### ISSUE TITLE
Move from `oslo` to `@oslojs/*` packages

### ISSUE THREAD

**Issue by adelrodriguez** [better-auth/better-auth#674]
[Oslo](https://github.com/pilcrowonpaper/oslo) is getting deprecated at the end of this year, and the recommendation is to use the packages under the [Oslo project](https://oslojs.dev/) which are (almost) a 1:1 export of the original Oslo.

This would also get rid of the `Package oslo can't be external` warnings that pops up on the console when using this package in Next.js.

I'm happy to tackle this if needed, I took a quick glance at the code and moving to the new packages should be pretty straightforward.

(Awesome work by the way! I'm really liking what you've done with this library)

**Comment by Bekacru** [comment]
Hey, thanks! The plan is to not depend on Oslo packages altogether. Since we only use a small subset of utilities, we can move them internally. If you want to take a look, feel free to do so :)

**Comment by adelrodriguez** [comment]
Got it! Yeah, I noticed there's a lot of overlap with other utilities as well, so I can take a stab into moving them internally or replacing them with other packages that are more widely used in the codebase.
