### ISSUE TITLE
Better-auth Not Working with React Router v7

### ISSUE THREAD

**Issue by ASgmbv** [better-auth/better-auth#677]
**Describe the bug**
I am getting the following error when trying to use integrate with React Router v7
```
[better-call]: Make sure the URL has the basePath (//api/auth).
```

My setup:

```
// auth.ts
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "~/db";

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "sqlite",
  }),
  emailAndPassword: {
    enabled: true,
  },
});
```

```
// auth-client.ts
import { createAuthClient } from "better-auth/react";

export const authClient = createAuthClient({
  baseURL: "http://localhost:5173",
});

```

```
// auth-routes.tsx
import { auth } from "~/lib/auth";
import { Route } from "./+types/auth";

export async function loader({ request }: Route.LoaderArgs) {
  return auth.handler(request);
}

export async function action({ request }: Route.ActionArgs) {
  return auth.handler(request);
}

```

```
// routes.ts
export default [
  route("api/auth/*", "./routes/auth.tsx"),
   ...
]
```

**Comment by Bekacru** [comment]
what framework are you using to run the backend?

**Comment by ASgmbv** [comment]
React Router v7 itself, it is the next major version of Remix after v2.

**Comment by jwstn** [comment]
@ASgmbv how did you resolve this issue?

**Comment by razrinn** [comment]
hi @Bekacru im trying to use better-auth with freshly create react-router v7, but when i'm trying to use hooks `authClient.useSession` I got this error.

<img width="1017" alt="Image" src="https://github.com/user-attachments/assets/1f01ee02-60bd-44de-bbe8-6fbbbdcac8a7" />

![Image](https://github.com/user-attachments/assets/742c84ac-364a-4668-ab23-6b7ebfe2c390)

![Image](https://github.com/user-attachments/assets/6271a5e7-18ed-4f7c-abb4-cf56aa20bb78)
