### ISSUE TITLE
Have an exported AuthClient type (analog to the Auth exported type for server-side)

### ISSUE THREAD

**Issue by bfovez** [better-auth/better-auth#680]
**Is your feature request related to a problem? Please describe.**
I would like to factorize an instance of `authClient `created by `createAuthClient({ baseURL })`

**Describe the solution you'd like**
Have an exported `AuthClient` type, analog to the `Auth` type for server-side.

**Comment by Bekacru** [comment]
You can just use `ReturnType<typeof createAuthClient<any>>`, but I still wouldn't recommend inferring the auth client like that, as it relies on a lot of generic inference. (same for `Auth`)

**Comment by bfovez** [comment]
Thank for the tip.
