### ISSUE TITLE
Type error when using admin plugin

### ISSUE THREAD

**Issue by jaspreet-singh-96** [better-auth/better-auth#682]
**Describe the bug**
I am getting below error when using admin plugin in NextJS.

**To Reproduce**
Add admin() in auth config.

**Expected behavior**
Auth should work without type error.

**Screenshots**
<img width="909" alt="image" src="https://github.com/user-attachments/assets/509e2cb3-2c6c-4863-9d02-8a2956ca8fda">
<img width="909" alt="image" src="https://github.com/user-attachments/assets/6e9dbdf1-76ce-455a-8eee-bdc1b7f5459d">

**Desktop (please complete the following information):**

- OS: MacOS 15
- Browser: Chromium
- Version: 131

**Comment by Bekacru** [comment]
make sure to set `declaration:false` in your tsconfig.

https://www.better-auth.com/docs/concepts/typescript#declaration-files

**Comment by jaspreet-singh-96** [comment]
working

**Comment by rhyek** [comment]
Also not working with `exactOptionalPropertyTypes` enabled.
