### ISSUE TITLE
Add abililiy to disable user Registration

### ISSUE THREAD

**Issue by daddasoft** [better-auth/better-auth#684]
**Is your feature request related to a problem? Please describe.**

Add abililiy to disable user Registration on  internal use app so only admin create accounts

**Comment by avanderbergh** [comment]
Am I missing something? `better-auth` gives you the tools to implement user registration, but it doesn't mean you have to do it...

You can simply choose not to implement it... 😅

**Comment by daddasoft** [comment]
no i didnt mean that i mean like if some one now im using better auth and try to create a user by the api not the code part

**Comment by daddasoft** [comment]
![image](https://github.com/user-attachments/assets/0a9e40a3-b7ad-4710-9f74-abea2550e096)

**Comment by daddasoft** [comment]
in this case i didnt have a register page but i create it just by api

**Comment by avanderbergh** [comment]
> in this case i didnt have a register page but i create it just by api

Ah, I see... So the `sign-up` endpoint is always created.

It might be good to have an option on the `emailAndPassword` to disallow sign-ups.

In the meantime, there might be a workaround...

I see there is a `databaseHooks` prop on [`BetterAuthOptions`](https://www.better-auth.com/docs/reference/options) which allows you to define custom hooks that can be executed during lifecycle of core database operations.

So, you could add some code to the `user.before` hook that simply returns `false`. Or do something like only allowing email from a certain domain. Or checking an `invite` table to something else...

**Comment by daddasoft** [comment]
good thanks a lot 

but a boolean toggle in wort it and easy
