### ISSUE TITLE
[Feature Request] Set Default Active Organization in Backend

### ISSUE THREAD

**Issue by ayushsharma82** [better-auth/better-auth#685]
**Describe the solution you'd like**

Currently, user can only set an active organization per session but we should be able to set a default active organization in backend/database. This way user will not have to select an active organization upon every new session. This reduces friction a bit and makes frontend a bit easier to handle as well.

**Comment by ayushsharma82** [comment]
@Bekacru  Appreciate the work around but this still requires some effort from the developer to store/persist active organization in some store or different table. 

Is it possible to add it in the database schema of user or organization itself to auto inject active organization? I was hoping for methods by which we can store it in backend itself.

**Comment by Bekacru** [comment]
The concept of `activeOrg` in the session table is primarily a utility to track the active organization globally, especially if you enforce that only one organization can be active at a time. But, this is not the case for most applications, as users should typically be able to have multiple organizations or workspaces open simultaneously in different tabs. 

When enforcing a single active organization, `activeOrg` can be used, and it is also useful for Better Auth's internal use cases. However, if you want to persist the active organization between sessions, this decision should be left to the application owner. It could default to the last active organization, a personal organization created by default, or any other logic determined by the application. This cannot be decided at the library layer.

**Comment by ayushsharma82** [comment]
> However, if you want to persist the active organization between sessions, this decision should be left to the application owner. It could default to the last active organization, a personal organization created by default, or any other logic determined by the application. This cannot be decided at the library layer.

I have to respectfully disagree, I believe you are can hit both targets with one stone but it's up for you to evaluate. From my perspective, all it needs is a `client.organization.setDefault` function that takes organization Id or a `null` value. 

For Example:
If we invoke setDefault with a organization Id, then the default organization gets saved in database and gets injected automatically upon new sessions. If we invoke it with `null` then it should clear the entry in DB and revert back to your existing logic of not setting any active organization on new sessions. This is pretty self explanatory to devs and works both ways.

**Comment by ayushsharma82** [comment]
> When enforcing a single active organization, activeOrg can be used

@Bekacru  Maybe you understood it wrong? I'm only asking for a persisted organization Id which gets set when user signs in, (i.e. when a fresh session is created) after that he can change the organization freely according to his will for the rest of the session.

**Comment by Bekacru** [comment]
This would require the plugin to add a `defaultOrgId` field (or similar) to the user table by default. But, this field may not have any use case unless you’re actively using this feature, and I don't think it’s a common use case. You might prefer to use the last active organization ID as the default when the user logs in. Or, you might not want any organization attached by default and simply treat the absence of an organization as the user being in their personal organization. 

And as much as possible, we try to avoid bloating the database with unnecessary fields that users may not use. Since Better Auth operates within your app’s db, we try to include only essential fields.

**Comment by Bekacru** [comment]
This could be its own plugin or an implementation layer on the application side. It should be straightforward to set up.

**Comment by focux** [comment]
My use case is to select the last active org, is there a hook to listen to active organization changes so we can implement this logic?

Edit.
I just found out about the session after update hook and I think that could work for my use case.

**Comment by nicolaslopezj** [comment]
You can do this to maintain the active org id after logout

```ts
databaseHooks: {
  session: {
    create: {
      async before(session) {
        const activeOrganizationId = await usersRepo.getUserDefaultOrganizationId(session.userId)
        return {
          data: {
            ...session,
            activeOrganizationId,
          },
        }
      },
    },
    update: {
      async after(session) {
        await usersRepo.setUserDefaultOrganization(
          session.userId,
          (session as any).activeOrganizationId,
        )
      },
    },
  },
},
```

**Comment by bismitpanda** [comment]
I may be **very** late to this, but you can do this with `additionalFields` in the auth config. Add a field `defaultOrganizationId` which is required and initially `""`. Then using database hooks, after a user signs up and you create the organization, update the user with the created organization's id.
