### ISSUE TITLE
Q: hasPermission - role

### ISSUE THREAD

**Issue by impactvelocity** [better-auth/better-auth#691]
Great project!

Quick question for the organizaiton.hasPermission 

https://www.better-auth.com/docs/plugins/organization#access-control-usage

const canCreateProject = await client.organization.hasPermission({
    role: "admin",
    permission: {
        project: ["create"]
    }
})

It seems to work with or without passing the role. I wonder why you need to pass the role? Wouldn't the role be inherited from the active user? Which it seems to be doing.

So I am just passing the permissions, and that is working. 

Just wanted to ask and make sure I am understanding it.

**Comment by salvinoto** [comment]
As far as I'm aware I believe the example is showing you can do either or. Meaning you can pass in the role you want it to be OR the specific permission.

**Comment by Bekacru** [comment]
The docs were wrong. it doesn't require roles.
