### ISSUE TITLE
Use localStorage?

### ISSUE THREAD

**Issue by arthur-fontaine** [better-auth/better-auth#7]
The documentation mentions that better-auth uses cookies to store the session.

I never tried, but I think that React Native can't handle server set cookies, and I didn't see anything in the documentation that tells how to change how sessions are stored.

So my question is, **_is there a way to use another storage than cookies?_**

By reading your code, I think it is only feasible with plugins but not with an option. I guess that if we use plugins, we lose a bit of the ease of better-auth so I think that it should be options to `getSessionFromContext` and `addSessionToRequest`.

**Comment by Bekacru** [comment]
You can use the bearer plugin. https://www.better-auth.com/docs/plugins/bearer

It'll allow you to send the session as Authorization Header. Better react native / expo support will be added down the road.

**Comment by arthur-fontaine** [comment]
Ah okay, I didn't see it. Thank you!
