### ISSUE TITLE
more control around deleteUser

### ISSUE THREAD

**Issue by arfath-linklet** [better-auth/better-auth#708]
**Is your feature request related to a problem? Please describe.**
Client provides a way to `deleteUser`. There is no guard in order to control this behaviour. We may need configurations for disabling this API.

Example useCases: when user has a subscription with dues, cleanup jobs before and/or after delete

**Describe the solution you'd like**
1. hooks for before and after delete
2. config for disabling delete API entirely

**Comment by Bekacru** [comment]
Hey, you can currently disable it by creating a plugin or checking in your handler if the pathname contains `/delete-user`. But, we plan to add more configurability around this in 1.1.0. Regarding hooks, we are working on a new API to handle them better, but for now, you can create a plugin to address this as well.
