### ISSUE TITLE
Typescript error - client's `updateUser` to have nullable fields and not optional

### ISSUE THREAD

**Issue by arfath-linklet** [better-auth/better-auth#711]
**Describe the bug**
User should be able to unset name and/or image.

```
updateUser({
  image: null,
  name: null,
});
```

This throws a typescript error as it expects string | undefined but works when force invoked with null

**Comment by Bekacru** [comment]
name cannot be null, as it is a required field. but we should allow it for image.

**Comment by Nicolab** [comment]
Hello,

Very useful (thanks!), but there seems to be an issue. If we pass only the property `image`, the field is not updated to the DB. With Drizzle in my case.
If I add a second field, that works.

Example (work-around) : 

```ts
updateUser({
  image: null,
  _nonce: Date.now(),
});
```
