### ISSUE TITLE
ElysiaJS Compatibility

### ISSUE THREAD

**Issue by xKesvaL** [better-auth/better-auth#72]
I love the simplicity and "humanity" of this library and I would love to use it with [ElysiaJS](https://elysiajs.com/) but since Elysia is quite different than any express-like framework, it would need its own implementation.

Any plan to do that?

**Comment by xKesvaL** [comment]
Current problem is when you pass the request to the handler, it tries accessing the body but Elysia has already parsed it so it will error.
My workaround for now :

```ts
.onParse(({ request, route }) => {
    // don't parse body if route is auth
    if (route.startsWith("/api/auth")) {
        return request.body;
    }
})
.all("/api/auth/*", ({ request }) => {
    return auth.handler(request);
});
```

**Comment by Bekacru** [comment]
yeah I'm not familiar with Elysia if you like to make integration, I would love to merge it :))

**Comment by xKesvaL** [comment]
Will look into that when I have time! :)

**Comment by Bekacru** [comment]
#155

**Comment by yukikwi** [comment]
> Current problem is when you pass the request to the handler, it tries accessing the body but Elysia has already parsed it so it will error. My workaround for now :
> 
> ```ts
> .onParse(({ request, route }) => {
>     // don't parse body if route is auth
>     if (route.startsWith("/api/auth")) {
>         return request.body;
>     }
> })
> .all("/api/auth/*", ({ request }) => {
>     return auth.handler(request);
> });
> ```

request.body work for me
![image](https://github.com/user-attachments/assets/23324c64-a69c-4fbe-a6af-135170d4f7dc)

Code
```ts
const betterAuthView = (context: Context) => {
  const BETTER_AUTH_ACCEPT_METHODS = ["POST", "GET"]
  // validate request method
  if(BETTER_AUTH_ACCEPT_METHODS.includes(context.request.method)) {
    console.log(context.request.url)
    console.log(context.request.body)
    return auth.handler(context.request);
  }
  else {
    context.error(405)
  }
}

const appPrefix = "/api/auth"
const app = new Elysia({ prefix: appPrefix })
  .all("/*", betterAuthView)
```
