### ISSUE TITLE
Sorry, this is probably not a bug but my error

### ISSUE THREAD

**Issue by ghost** [better-auth/better-auth#730]
Hi, I can log in and get a session returned. And I can see the session in my db.

 ```
try {
    const { error, data } = await authClient.signIn.emailOtp({
      email: validatedFormData.data.email,
      otp: validatedFormData.data.otp,
    });
    if (error) {
      return {
        success: false,
        message: 'Authentication failed! Please try again.',
      };
    }

    console.log('DATA: ', data);
    console.log('SESSION: ', data?.session);
    console.log('USER: ', data?.user);
```

But then I can't access the session and I don't see a cookie in my dev tools.

```
import { authClient } from '@/lib/auth-client';

export default async function ProfilePage() {
  const { data } = await authClient.getSession();

  console.log(data);
  console.log(data?.user);
  console.log(data?.session);
}
```

**Comment by Bekacru** [comment]
```tsx
import { authClient } from '@/lib/auth-client';
import { headers } from "next/headers";

export default async function ProfilePage() {
  const { data } = await authClient.getSession({
    headers: await headers(),
  });
}
```

When you call `authClient.getSession` on the server, you need to pass the headers as a `fetchOption`. This will make an HTTP round trip from your server to your own server. Alternatively, you can use `auth.api.getSession` to avoid that. However, using `getSession` this way has the benefit of updating the cookie if the session has reached its update age.

**Comment by ghost** [comment]
Thank you so much for this!!

**Comment by ghost** [comment]
Do i need to set the headers somewhere? 
I'm still getting null for the session with this.

```
const { data } = await authClient.getSession({
    fetchOptions: {
      headers: await headers(),
    },
  });
```

**Comment by ghost** [comment]
I also don’t see any cookie in my chrome dev tools

**Comment by hossdar** [comment]
I am at the same spot ```signIn.emailOtp``` successfully created the session in the database, but nothing in the client! session cookies not shown my dev tools !

Help please, and thank you guys for the amazing work 👍

**Comment by ghost** [comment]
Agreed. Love this project.

**Comment by Bekacru** [comment]
If you're trying to call `authClient.signIn.emailOTP` on the server, don't. `authClient` is meant to be called on the client, if it's not called on the client it can't set the cookie. If you need to use server actions you can use `auth.api.signInEmailOTP` instead and make sure to add `nextCookies` in your plugins list.

**Comment by ghost** [comment]
do you mean this plugin:
import { bearer } from "better-auth/plugins";

**Comment by Bekacru** [comment]
no read the docs here https://www.better-auth.com/docs/integrations/next#server-action-cookies

**Comment by ghost** [comment]
Thank you, appreciate this help.

**Comment by ghost** [comment]
Thanks again. It's working now.
