### ISSUE TITLE
OAuth Error (oauth_code_verification_failed)

### ISSUE THREAD

**Issue by xKesvaL** [better-auth/better-auth#74]
I've tried both with Elysia and Hono but I can't make Google OAuth2 work, I always get the same error :

![image](https://github.com/user-attachments/assets/3a7d3c81-000f-47f8-98b5-823cac1b7511)

My google oauth scopes seem fine:

![image](https://github.com/user-attachments/assets/8d200aa1-3397-4cb2-bf11-c0a14506cd47)

And it seems like I'm not the only one having these kinds of problems: #24 

https://github.com/xKesvaL/supacoach/tree/xkesval/auth-error
https://github.com/xKesvaL/supacoach/tree/xkesval/auth-error-hono

Here are two branches in my repo where I can reproduce the issue.

**Comment by Bekacru** [comment]
It seems the issue was with NODE_ENV not being set correctly, which caused secure cookies to be used in development. This should be resolved in the latest update.

**Comment by Bekacru** [comment]
I'm gonna close this. feel free to re-open if it's still the case.

**Comment by xKesvaL** [comment]
Completely forgot to close this, but it was indeed fixed! Thanks :)
