### ISSUE TITLE
Error Handling in authClient.signIn.email Doesn't Catch All Errors

### ISSUE THREAD

**Issue by adrian-kong** [better-auth/better-auth#740]
**Describe the bug**
The authClient.signIn.email function, as implemented from the docs, fails to catch all errors, such as Cross-Origin Request Blocked errors caused by CORS policy violations. This happens because the current implementation relies solely on the onError callback provided in the options, which does not account for errors thrown at a higher level.

**To Reproduce**

As example in docs:
```js
      await authClient.signIn.email(
        { email, password },
        {
          onRequest: () => {
          },
          onSuccess: () => {
          },
          onError: (ctx) => {
            console.error(ctx.error.message);
          },
        }
      );
```
will error in backend 
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource
```

**Expected behavior**
onError should handle the error or docs to be updated with try catch

**Comment by Bekacru** [comment]
that's is intentional behavior. It only supposed to catch api returned errors.
