### ISSUE TITLE
"token" does not exist in the schema

### ISSUE THREAD

**Issue by productdevbook** [better-auth/better-auth#741]
Where's the whole shema for Drizzle? I didn't see it in the docs.

```
 INTERNAL_SERVER_ERROR The field "token" does not exist in the schema for the model "session". Please update your schema.
 ```

**Comment by Bekacru** [comment]
we don't provide drizzle schema in the docs. You either need to generate one using the cli or see the expected schema from the docs 

https://www.better-auth.com/docs/concepts/database#session

**Comment by productdevbook** [comment]
Thank you ❤️
