### ISSUE TITLE
Admin Plugin: user can login after ban

### ISSUE THREAD

**Issue by erickleinde** [better-auth/better-auth#747]
**Describe the bug**
After a user was banned, they were still able to log in

**To Reproduce**

1. Ban user
2. login with your banned user

**Expected behavior**
User should no longer be able to log in after the ban

**Screenshots**
Screenshot from DB:
![image](https://github.com/user-attachments/assets/1dd085c9-754c-4923-b20e-237b02abafba)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome
- Version: 131.0.6778.86

**Comment by Bekacru** [comment]
The ban protection is enforced at the session creation level. This means that just before a session is created, if the user is banned, a session will not be generated for them. However, they can still go through the authentication flow—for example, if they are using OAuth, or they might still receive an email OTP if you are using email-otp. The ban is enforced precisely when the authentication method attempts to generate a session. 

If, for any reason, this is bypassed and a session is actually being generated for a banned user, please let me know which authentication method you are using

**Comment by erickleinde** [comment]
Ah sorry, my mistake. I was using an old version of better auth. 😅 everything works with the current one. 🙂
