### ISSUE TITLE
getActiveOrganization how should such an algorithm be written or where does it come from? 

### ISSUE THREAD

**Issue by productdevbook** [better-auth/better-auth#760]
We don't keep this value in the database, if we want to send headers, we can't get it because the event doesn't return. What should we do.

```ts
export const auth = betterAuth({
  databaseHooks: {
      session: {
          create: {
              before: async(session, // event(request) no see params // )=>{
                  const organization = await getActiveOrganization(session.userId)
                  return {
                    data: {
                      ...session,
                      activeOrganizationId: organization.id
                    }
                  }
              }
          }
      }
  }
})
```

**Comment by Kabeer10** [comment]
i believe you just use your own logic. like get users Organizations form DB using ur own way. SQL, mongo or any ORM.

**Comment by Bekacru** [comment]
not sure what exactly you're trying to achieve but if you mean that your `getActiveOrg` logic depends on the request object could you tell me how exactly? (just to gather the use case)

**Comment by Benjamin-Lee** [comment]
Bringing in my own use case: I want to make the base case of a user being a member of only a single organization simpler by automatically making their active organization the only one it could be.

**Comment by radosek** [comment]
@Bekacru it is related to [this](https://www.better-auth.com/docs/plugins/organization#set-active-organization).
