### ISSUE TITLE
What is the plan for adding more Providers

### ISSUE THREAD

**Issue by guptaashwanee** [better-auth/better-auth#762]
**Is your feature request related to a problem? Please describe.**
### PingId provider support

**Describe the solution you'd like**
You can add more Identity Providers, as @authhs has.

**Describe alternatives you've considered**
I am using @authjs in my current setup. I want to explore more libraries as: better-auth

**Comment by Bekacru** [comment]
We only plan to add commonly used providers that can genuinely be considered "social" providers. For other OAuth providers, you'll need to use our generic OAuth plugin and pass your own configuration. In the future, we may provide a list of configurations, but we don't aim to maintain an exhaustive list of providers like Auth.js and other libraries. Said that, If you have a specific provider request that you think we should support by default, feel free to open another issue :)
