### ISSUE TITLE
Type errors when using `better-auth` in `next-forge`

### ISSUE THREAD

**Issue by trevorpfiz** [better-auth/better-auth#766]
**Describe the bug**
Type errors when using `better-auth` in `next-forge`

`The inferred type of 'auth' cannot be named without a reference to '.pnpm/better-call@0.3.3-beta.4/node_modules/better-call'. This is likely not portable. A type annotation is necessary.ts(2742)`
`The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.ts(7056)`
`The inferred type of 'signIn' cannot be named without a reference to '.pnpm/@better-fetch+fetch@1.1.12/node_modules/@better-fetch/fetch'. This is likely not portable. A type annotation is necessary.ts(2742)`

**To Reproduce**

1. Start project with [next-forge](https://www.next-forge.com/)
2. Follow [guide](https://docs.next-forge.com/authentication/better-auth) to switch to `better-auth`
3. I also followed [switch to drizzle](https://docs.next-forge.com/database/drizzle)

**Expected behavior**
I would expect there to be no type errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/781825c6-5c8f-43fc-9ced-72f5063f15df)
![image](https://github.com/user-attachments/assets/128a0635-120d-48ff-bfc8-b9cc93c823ff)
![image](https://github.com/user-attachments/assets/30c544bf-cfe8-4370-b8cc-aadcfe1baad3)

**Additional context**
This is a related discussion https://github.com/trpc/trpc/discussions/5636

**Comment by Bekacru** [comment]
does this happen after you have disabled `declaration`?

**Comment by SkidGod4444** [comment]
> amed without a reference

this type of things only happens on some IDE

**Comment by trevorpfiz** [comment]
> does this happen after you have disabled `declaration`?

the error goes away with:

```
"declaration": false,
"declarationMap": false
```

**Comment by catnaut** [comment]
I encountered this issue while using `better-auth/vue`:

```ts
import { createAuthClient } from 'better-auth/vue'

export const authClient = createAuthClient({
  baseURL: 'http://localhost:5173', // the base url of your auth server
})
```

**Error:**

```
The inferred type of 'authClient' cannot be named without a reference to '.pnpm/@better-fetch+fetch@1.1.12/node_modules/@better-fetch/fetch'. This is likely not portable. A type annotation is necessary. ts(2742)
The inferred type of 'authClient' cannot be named without a reference to '.pnpm/nanostores@0.11.3/node_modules/nanostores'. This is likely not portable. A type annotation is necessary. ts(2742)
The type of this node cannot be serialized because its property '[iterator]' cannot be serialized. ts(4118)
The type of this node cannot be serialized because its property '[unscopables]' cannot be serialized. ts(4118)
```

**Comment by Bekacru** [comment]
> I encountered this issue while using `better-auth/vue`:

same. make sure to set `declaration:false` and `strict:true`

**Comment by Bekacru** [comment]
I'm gonna close this. This is already referenced in the docs https://www.better-auth.com/docs/concepts/typescript

feel free to open another issue if you're facing a related problem with ts.

**Comment by natew** [comment]
@Bekacru we have a build library that uses declarations only, having to work around this is causing us to have only one package in our repo be different. How hard would it be to allow this?

![CleanShot 2024-12-19 at 14 16 41@2x](https://github.com/user-attachments/assets/dfcd61ee-27a7-4427-86ca-0a41e8fa4990)

**Comment by Bekacru** [comment]
> @Bekacru we have a build library that uses declarations only, having to work around this is causing us to have only one package in our repo be different. How hard would it be to allow this?

just went through some issues and I think I found the issue. Could you try `1.0.23-beta.5` and see if it fixes it? The server `auth` instance may still have a problem, but the `authClient` should likely be fixed.

**Comment by ISnackable** [comment]
I tried installing `1.0.23-beta.6` but I am still having this issue. While setting `declaration: false` in tsconfig.json does "solve" the issue on the IDE side, when you try building the app this error still persists.

```bash
 > next build
│ 
│    ▲ Next.js 15.1.2
│    - Environments: .env
│    - Experiments (use with caution):
│      · reactCompiler
│ 
│    Creating an optimized production build ...
│  ✓ Compiled successfully
│    Linting and checking validity of types  ..Failed to compile.
│ 
│ ../../packages/auth/client.ts:9:14
│ Type error: The inferred type of 'client' cannot be named without a reference to '.pnpm/@si
│ mplewebauthn+types@10.0.0/node_modules/@simplewebauthn/types'. This is likely not portable.
│  A type annotation is necessary.
│ 
│    7 | import { createAuthClient } from 'better-auth/react';
│    8 |
│ >  9 | export const client = createAuthClient({
│      |              ^
│   10 |   baseURL: host, // the base url of your auth server
│   11 |   plugins: [organizationClient(), passkeyClient(), multiSessionClient()],
│   12 | });
│  ELIFECYCLE  Command failed with exit code 1.
│ command finished with error: command (/workspaces/next-forge/apps/app) /usr/local/share/npm-g
│ lobal/bin/pnpm run build exited (1)
└────>
app#build: command (/workspaces/next-forge/apps/app) /usr/local/share/npm-global/bin/pnpm run build exited (1)
```

Wondering if there's any workaround like manually typing the client?

Edit: Nvm, you also need to add `declaration: false` in the nextjs apps tsconfig. However, I hope this is eventually fixed...

**Comment by luskin** [comment]
For what it's worth, this issue only exists for us when adding the `passkey` plugin to the plugins array. Removing that plugin produces no typescript errors.
