### ISSUE TITLE
[docs-improvement]: Guide to add your own auth provider

### ISSUE THREAD

**Issue by jorgeorejas** [better-auth/better-auth#770]
**Is your feature request related to a problem? Please describe.**

I'm trying to build tools to automate tasks in startups, many startups (almost all) use slack as their communication channel, so I would love to be able to authenticate and send messages in a slack organization.

**Describe the solution you'd like**

A guide so any can add their specific needed oauth provider would be probably enough

**Describe alternatives you've considered**

I wouldn't mind if you add slack as a provide, I do think many people would use it and it would add a lot of value.

**Comment by Bekacru** [comment]
Hey, you can use https://www.better-auth.com/docs/plugins/generic-oauth to add a custom oauth provider. But we'll consider adding slack as a social provider!

**Comment by Bekacru** [comment]
I'm gonna close this. Feel free to re-open another issue for slack as a social provider request.
