### ISSUE TITLE
How to configure electron to support it?

### ISSUE THREAD

**Issue by zhaopengme** [better-auth/better-auth#783]
How to configure electron to support it?

**Comment by mobailabs** [comment]
Maybe I found a bug, so I turned it off first and I'll look for it.

**Comment by hammer-ai** [comment]
Did you get it working with Electron? How did you do it?

**Comment by gyanendrasng** [comment]
did you get to work? @zhaopengme @hammer-ai

**Comment by luc-debug** [comment]
How did you get it to work @zhaopengme ?

**Comment by gyanendrasng** [comment]
@SaadBazaz I made a custom plugin for it
