### ISSUE TITLE
Invalid currentURL in production mode when login with provider

### ISSUE THREAD

**Issue by Moumouuu** [better-auth/better-auth#787]
**Describe the bug**
Only in production i have this error when I try to sign in with a provider like google : 
message : Invalid currentURL
code : INVALID_CURRENTURL

The URL of the request : (POST)
https://xx.yyy.fr/api/auth/sign-in/social?currentURL=https://xx.yyy.fr/sign-in

**Screenshots**

Request :
<img width="159" alt="Capture d’écran 2024-12-06 à 18 26 24" src="https://github.com/user-attachments/assets/0849300e-3dbe-4e5e-8856-9ee49d548fe5">
Response : 

<img width="217" alt="Capture d’écran 2024-12-06 à 18 26 05" src="https://github.com/user-attachments/assets/fedbe30c-938b-43ad-9841-c6acfc793088">

**Comment by Bekacru** [comment]
make sure to include your frontend url in `trustedOrigins` list

**Comment by Moumouuu** [comment]
> make sure to include your frontend url in `trustedOrigins` list

Thanks, it works! But where is this information in the documentation?
I’m using Next.js, and my app combines both the backend and the frontend. Am I missing something?

By the way, thank you so much for what you’re doing I love it!

**Comment by Bekacru** [comment]
Hey thanks! If your just using next, it should work. Maybe you have set `BETTER_AUTH_URL` to a wrong value in prod.

**Comment by Moumouuu** [comment]
The value in prod is correct, maybe I make a mistake somewhere..    In all cases, thanks for you help and your reactivity :)
