### ISSUE TITLE
better-fetc with better auth keeps redirecting me 

### ISSUE THREAD

**Issue by firstaxel** [better-auth/better-auth#797]
i am working on a monorepo with better auth but upon using the better-fetch to fetch the session in the middleware i am getting redirected countless times that the page wont load please check it out using the same middleware config as the better-auth nextjs demo 

P.S it doesnt fetch the session i think that is why there a lot of redirection
Also API for my app is a microservice meaning i splitted it into a different nextjs app with it use only for my api but everything is configured correctly cause i was able to use to use authClient and auth api severside with the auth.api but i can get session cookies in the middleware with better-fetch

**Comment by Bekacru** [comment]
Check if the session is being fetched properly, and review your redirection logic in case it might be causing an infinite redirection loop.

**Comment by firstaxel** [comment]
Fixed thanks very much

**Comment by firstaxel** [comment]
Closing now

**Comment by jessaleks** [comment]
@firstaxel what did you do to fix the issue?
