### ISSUE TITLE
Redirect after SignOut

### ISSUE THREAD

**Issue by emersonlaurentino** [better-auth/better-auth#798]
After Sign Out, I want to redirect, so I think this can be like that:

Manually
```tsx
signOut({
  redirectUri: "/login"
})
```

or by config

```tsx
createAuthClient({
  baseURL: import.meta.env.VITE_API_URL,
  signOutRedirectUri: "/login",
});
```

**Comment by Bekacru** [comment]
you should redirect yourself using your framework router or using window.location yourself using `onSuccess` callback. This is to avoid hard redirects.

```ts
signOut({
   fetchOptions: {
     onSuccess: async()=>{
        //redirect here
    }
  }
})
```

**Comment by emersonlaurentino** [comment]
great, it's work for me
