### ISSUE TITLE
Column name in snake_case

### ISSUE THREAD

**Issue by emersonlaurentino** [better-auth/better-auth#799]
Just like `usePlural`, would be nice if the database drizzleAdapter config has an `useSnakeCase` to generate the column names in snake_case.

Example:

```tsx
betterAuth({
  database: drizzleAdapter(db, {
    provider: "sqlite",
    usePlural: true,
    useSnakeCase: true,
  }),
});
```

the schema is like that:

```tsx
// ...
  expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(),
// ...
```

**Comment by Bekacru** [comment]
for drizzle, prisma... snake case should be handled by the adapter instead. Better Auth only interacts with the orm layer. meaning in your case it only cares what you named your keys not the actual mapping in your db.

**Comment by Bekacru** [comment]
we plan to support it for the builtin Kysely adapter but there is open issue at #410 already

**Comment by emersonlaurentino** [comment]
> for drizzle, prisma... snake case should be handled by the adapter instead. Better Auth only interacts with the orm layer. meaning in your case it only cares what you named your keys not the actual mapping in your db.

but when I run the migrate command by CLI, the map is in camelCase, that's my point.

**Comment by svaraborut** [comment]
Yes, the `migrate` command is used for the builtin Kysely which as mentioned by @Bekacru does not yet support snake_case and is tracked separately in https://github.com/better-auth/better-auth/issues/410 . Other adapters have their respective configuration for casing.
