### ISSUE TITLE
Better auth is fetch from localhost:3000 even though the Nextjs url is set (!urgent)

### ISSUE THREAD

**Issue by salmansheri** [better-auth/better-auth#800]
**Describe the bug**
Better Auth is fetching from localhost:3000 even though the base URL is set 

**Expected behavior**
Should fetch from provided url 

**Screenshots**
![Screenshot_2024-12-07-11-41-24_1366x768](https://github.com/user-attachments/assets/d6bd6d05-6c6a-4f1e-b5db-22a60df4355e)

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser Firefox (132.0.2) both incognito and normal window

**Comment by Bekacru** [comment]
check your authClient base url

**Comment by salmansheri** [comment]
> check your authClient base url

![Screenshot_2024-12-08-07-20-24_1366x768](https://github.com/user-attachments/assets/99e6aedb-1da1-49ea-ab22-04166a2cf084)

I Changed the environment variable in vercel but it is again fetching from localhost:3000 and making CORS Error I tried redeploying but it just never works 

![Screenshot_2024-12-08-07-21-22_1366x768](https://github.com/user-attachments/assets/75031737-67fc-4a11-ae2f-6bce7836d5ac)

**Comment by Bekacru** [comment]
No I was asking for the authClient where you initiating the client

**Comment by salmansheri** [comment]
> No I was asking for the authClient where you initiating the client

![Screenshot_2024-12-08-13-12-03_1366x768](https://github.com/user-attachments/assets/c95cec8d-cdff-4093-95b3-27ae555b356d)

I assume you were asking this one right

**Comment by Bekacru** [comment]
no. where you called `createAuthClient` make sure to pass the right `baseURL` 

```ts
createAuthClient({
 baseURL: //
})
```

**Comment by salmansheri** [comment]
> no. where you called `createAuthClient` make sure to pass the right `baseURL`
> 
> ```ts
> createAuthClient({
>  baseURL: //
> })
> ```

Thank you for your help sir I found Thank you very much

**Comment by salmansheri** [comment]
> no. where you called `createAuthClient` make sure to pass the right `baseURL`
> 
> ```ts
> createAuthClient({
>  baseURL: //
> })
> ```

Issue solved Thank you
