### ISSUE TITLE
API function to verify password

### ISSUE THREAD

**Issue by JE4GLE** [better-auth/better-auth#803]
**Is your feature request related to a problem? Please describe.**
Currently, I cannot verify the password on the server side to authenticate actions. For example, "Enter your password to delete this item".

**Describe the solution you'd like**
```javascript
const isCorrect: boolean = await auth.api.verifyPassword({
    password,
});
```

**Describe alternatives you've considered**
Manually getting the data from the database and verifying it. This is somewhat hacky and I would not prefer it.

**Comment by JE4GLE** [comment]
Nice would be an option to add it as a password entry try to limit requests. For example:

```javascript
const isCorrect: boolean = await auth.api.verifyPassword({
    password,
    limited: true
});
```

With `limited` having `false` as a default value.

**Comment by Bekacru** [comment]
you can use the ctx api (which isn't documented yet)

```ts
const ctx = await auth.$context;
await ctx.password.verify({password: "", hash: ""});
```

It should be documented soon

**Comment by SaviruFr** [comment]
Hey @Bekacru, any chance we could still get something like auth.api.verifyPassword?
