### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by devshahoriar** [better-auth/better-auth#804]
Next js standalone build host on Cpanel everything working file in "bun dev" but when "bun run build" and standalone build host to cpanel get this error :
![Screenshot (9)](https://github.com/user-attachments/assets/5482b130-aae6-4320-a0f8-bfc7baad8c13)

I have done -> 
![Screenshot 2024-12-07 224007](https://github.com/user-attachments/assets/a3da774e-95ce-4dce-990c-15594db0cf37)
![Screenshot 2024-12-07 223953](https://github.com/user-attachments/assets/f392b134-5f8d-4167-81ec-0f2d123031d3)
![Screenshot 2024-12-07 223943](https://github.com/user-attachments/assets/393c2ba6-5726-4ff5-a449-365aa88457ee)

**Comment by sohamnandi77** [comment]
Where is BETTER_AUTH_URL ? that is required to pass i guess

**Comment by devshahoriar** [comment]
![Screenshot 2024-12-07 232155](https://github.com/user-attachments/assets/a8899bbc-8876-49d4-b165-4b04be7354e7)
![Screenshot 2024-12-07 232146](https://github.com/user-attachments/assets/507af60e-e53e-4421-8669-ba23927e7152)

**Comment by devshahoriar** [comment]
![Screenshot 2024-12-07 232234](https://github.com/user-attachments/assets/87b42a7b-0259-4101-bcd2-aacbc1b13959)

??

**Comment by Sama-004** [comment]
is APP_URL there in the env?

**Comment by devshahoriar** [comment]
I discovered it after about 10 hours."trustedOrigins" mast be given to production.

![Screenshot 2024-12-08 115100](https://github.com/user-attachments/assets/b11d8c9f-a134-4b60-b727-2655b0a16656)
![Screenshot 2024-12-08 115029](https://github.com/user-attachments/assets/1f069839-fbae-44eb-bcd0-0ecf1117e9a1)

**Comment by devshahoriar** [comment]
"trustedOrigins" mast be given to production.
