### ISSUE TITLE
How to resend a verification email?

### ISSUE THREAD

**Issue by Nicolab** [better-auth/better-auth#809]
Hello,

First, thanks for this very handy lib 👍

Is there a way to resend the verification email (the one for registration)?

**Is your feature request related to a problem? Please describe.**
If the user fails to retrieve the verification email in time (or if the token expires), the user's account is dead. A dev will have to intervene, or the user will have to recreate an account with another email, which is not good for the user experience.

**Describe the solution you'd like**
A way to resend verification email.

**Comment by Sama-004** [comment]
![image](https://github.com/user-attachments/assets/828b3ffc-c54f-4f32-b3f6-41d8750e2359)

https://www.better-auth.com/docs/concepts/email#3-manually

I think this will do what you're expecting

**Comment by Nicolab** [comment]
Yeah, thank you @Sama-004!
The worst thing is that I read it over and over again, I missed it. My eyes didn't want to see it, a bit like the brick in a pocket that we look for all over the room 😅

**Comment by Sama-004** [comment]
> Yeah, thank you @Sama-004! The worst thing is that I read it over and over again, I missed it. My eyes didn't want to see it, a bit like the brick in a pocket that we look for all over the room 😅

happens to the best of us, haha :sweat_smile:
