### ISSUE TITLE
Rename `integrations` to `frameworks` in the docs.

### ISSUE THREAD

**Issue by Multinite** [better-auth/better-auth#811]
**Is your feature request related to a problem? Please describe.**
"Integrations" can be somewhat confusing, I've scanned the entire docs and improved it over time with a few contributions, but despite personally only use Next.js, when I saw integrations, I never thought to click into it.
<img width="278" alt="image" src="https://github.com/user-attachments/assets/bf0a66d3-d45a-4759-8ea3-be85f4b5500a">

"Frameworks" may be a less confusing name for it. For users who have concerns or want to know what to do around using Better auth in their choice of framework, this makes sense.
> Though I understand that integrations is like "integrating better auth", I still believe that `frameworks` sounds easier to understand. 

**Describe the solution you'd like**
Rename `integrations` section in the docs to be `frameworks`.

**Additional context**
<img width="801" alt="image" src="https://github.com/user-attachments/assets/7f0e6bb4-c439-4129-bf12-42744fe672cf">
It was this message by a user from the Discord server which made me think that I had the same conclusion too.
I never even considered checking "integrations". 
If he had saw "frameworks", he, and other users, may check it first while setting up better auth in their project, thus eliminating a lot of FAQ.

**Comment by ping-maxwell** [comment]
If you're happy with this, I'll happily update it for you.
And check other links in the repo if any *link* to the existing `integrations` docs to update their URL.

**Comment by Sama-004** [comment]
+1

**Comment by Bekacru** [comment]
I think it should stay as 'Integration.' Frameworks only describe some of the items listed, but 'Integrations' covers anything, framework or not. It’s about how Better Auth works with different 'things.' I get that it might be a bit confusing, so maybe we could add a link at the end of the installation section to point people to the integrations page along with basic usage.

**Comment by ping-maxwell** [comment]
Alright.
