### ISSUE TITLE
Move `demo/nextjs` to `examples/nextjs-example`

### ISSUE THREAD

**Issue by Multinite** [better-auth/better-auth#813]
**Is your feature request related to a problem? Please describe.**
Shouldn't the nextjs demo project be apart of the other example projects too?

**Describe the solution you'd like**
Move `demo/nextjs` to `examples/nextjs-example`

**Comment by ping-maxwell** [comment]
I can do this, just let me know if you want this.

**Comment by wrsrsh** [comment]
Yeah sure
