### ISSUE TITLE
new error in sveltekit integration (similar to #69)

### ISSUE THREAD

**Issue by nevthereal** [better-auth/better-auth#82]
I now just get a new error:
```
Cannot destructure property 'building' of '(intermediate value)' as it is undefined.
    at Module.svelteKitHandler
```

_Originally posted by @nevthereal in https://github.com/better-auth/better-auth/issues/69#issuecomment-2393235055_

**Comment by Bekacru** [comment]
Could you please confirm if this issue still occurs in the latest release (0.2.9-beta.9)?

**Comment by nevthereal** [comment]
it is now gone, thanks!
I will soon do a video about your work btw
