### ISSUE TITLE
docs: sidebar select menu not responsive

### ISSUE THREAD

**Issue by Sama-004** [better-auth/better-auth#832]
**Describe the bug**
in the [docs](https://www.better-auth.com/docs/introduction) there is a select menu on sidebar which allows to switch between the docs and examples but on mobile phone this select menu is not there

**To Reproduce**

1. Open the [documentation](https://www.better-auth.com/docs/introduction) on your phone and observe the sidebar there is not selection menu
2. Change to desktop mode to see the expected behavior of the selection menu

**Expected behavior**
select menu should be there on sidebar
![image](https://github.com/user-attachments/assets/e5545a38-cebb-4c39-a8b1-1bb76f187caf)

**Actual behavior**
no select menu to switch from docs to example
![image](https://github.com/user-attachments/assets/2c6b6bfa-14c9-449c-bcf8-8daa9a645eda)

**Comment by ping-maxwell** [comment]
@Sama-004 Maybe look to close this.
