### ISSUE TITLE
Invalid currentURL on nextjs coolify deploy

### ISSUE THREAD

**Issue by nytocode** [better-auth/better-auth#838]
**Describe the bug**
Sign in work correctly locally but when  deployed to coolify it gives "Invalid currentURL" error, the currentURL query parameter doesn't seem to be correct

**To Reproduce**

1. Deploy next app to coolify
2. Access the app via generated domain
3. Try to login (or any other api action

**Expected behavior**
I expect the app to behave as it behave locally

**Screenshots**
<img width="828" alt="Screenshot 2024-12-09 at 14 08 14" src="https://github.com/user-attachments/assets/1a14706d-a0bc-49a3-a7a2-ebf9acfac5b1">

**Additional context**
The app is deployed with sef hosted coolify

**Comment by Sama-004** [comment]
@nytocode have you changed the `BETTER_AUTH_URL` in the env

**Comment by nytocode** [comment]
@Sama-004  Yes I tried changing it and passing it directly in the client but seems not to work

**Comment by nytocode** [comment]
Found the problem. It seems I need to add my deploy url to trusedOrigins in better auth config
