### ISSUE TITLE
verifyOTP api 

### ISSUE THREAD

**Issue by amirhd-developer** [better-auth/better-auth#86]
**when I use phoneNumber.verify like this:**

![image](https://github.com/user-attachments/assets/8e666b57-361f-4b4f-9aae-fc588fc4c057)

**with this config on auth.ts:**

![image](https://github.com/user-attachments/assets/2ccd5405-9b3d-410e-a509-1a922ff11ae9)

### I get just this error on console:

![image](https://github.com/user-attachments/assets/d0d83fd7-9f0b-46c4-ad7f-a2e1dc123e7c)

while the better auth installation and database seems fine. the phoneNumber.sendVerificationCode is work good and I check database that save the phone number and the code successfully. but when I verify the code get the error at all.

* when I check verfication table and exiresAt column forexample for latest code, the time that saved by UTC, even my users in other region have time difference. when I edit time directly on database based on my region zone and then request to verify code, still get the error again *

**Comment by Bekacru** [comment]
You shouldn't pass verifyOTP, as the plugin automatically handles OTP verification. That was an undocumented API that doesn't work. Please update to the latest version and let me know if the issue persists.

**Comment by amirhd-com** [comment]
> You shouldn't pass verifyOTP, as the plugin automatically handles OTP verification. That was an undocumented API that doesn't work. Please update to the latest version and let me know if the issue persists.

Ok, I removed verifyOTP and config all require things again depend on lastest version, but still get 404 status and invalid code per request to phoneNumber.verify...

**Comment by Bekacru** [comment]
Could you please share me a reproduction? All of our tests are passing, so I'm not sure what's causing the issue on your end.

**Comment by amirhd-com** [comment]
I solved it by install better fetch library...

### npm i @better-fetch/fetch
