### ISSUE TITLE
NestJS - Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by arashi-dev** [better-auth/better-auth#862]
**Describe the bug**
The object's type returned from `betterAuth()` is too slow and takes about 10 seconds to iterate the types in NestJS. if I use any properties of the `auth.api` property, it gives me the error: `Type instantiation is excessively deep and possibly infinite`

**To Reproduce**

1. build a nest project using `npx  @nestjs/cli new my-project`
2. make a new `.ts` file somewhere in the `/src` directory
3. import the `betterAuth` and run simply call it.

**Expected behavior**
The type-intellisense must be much much much faster than this.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Node Version: 20.11.0
- Package Manager: Yarn
- Typescript Version (as from the official starter template, v5.1.3)

**Additional context**

###### tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}
```

**Comment by Bekacru** [comment]
set `declaration:false` and `strict:true` 

https://www.better-auth.com/docs/concepts/typescript

**Comment by arashi-dev** [comment]
@Bekacru Thanks. it worked
