### ISSUE TITLE
email OTP Verification not signing user in on verification success.

### ISSUE THREAD

**Issue by ionztorm** [better-auth/better-auth#868]
**Describe the bug**

1) The OTP plugin does not automatically issue a verification email on signup when the sendVerificationOnSignup option is set to true.

2) When successfully verifying the OTP, the user is not automatically signed in.

**To Reproduce**

1) No automatic OTP email sending
- Setup the OTP plugin.
- Create an account with email & password
// no email is sent

2) No automatic login.
- add the sendVerificationOtp func to the 1st setup, and repeat steps in 1)
- enter received Otp code into emailOtp.verifyEmail
// user is not logged in

**Expected behavior**

I would expect that setting sendVerificationOnSignup to true would automatically send an OTP to the users email when they submit a new username and password for a new account.

I would expect that the user is automatically logged in when the verification is successful.

**Comment by svaraborut** [comment]
I think neither conventional token verification performs automated sign-in after verification. This may be a bug we are carrying on since pre v1

**Comment by Bekacru** [comment]
1. I think it's probably because `emailVerified` is null. The plugin strictly checks for a `false` value. We should patch that.  
2. `sendVerificationOTP` doesn't sign in the user automatically. You should use `authClient.signIn.emailOTP` instead, which will sign in the user upon verification.

**Comment by leonlonsdale** [comment]
> 1. I think it's probably because `emailVerified` is null. The plugin strictly checks for a `false` value. We should patch that.
> 2. `sendVerificationOTP` doesn't sign in the user automatically. You should use `authClient.signIn.emailOTP` instead, which will sign in the user upon verification.

The sendVerificationOTP is fine, but if you send a verification email using sendVerificationOTP with type = email-verification and then attempt to use authClient.signIn.emailOTP, you get invalid otp error. Using authClient.emailOtp.verifyEmaill works with the otp but the user is not signed in when they verify.

> I think neither conventional token verification performs automated sign-in after verification. This may be a bug we are carrying on since pre v1

automated-sign in after verification works with the standard email verification method using the following options:

```ts
emailVerification: {
  sendOnSignUp: true,
  autoSignInAfterVerification: true,
  //...
}
```

It would be useful if emailOtp.verifyEmail did the same. From a dev pov it's no issue, we can redirect the user to login, but from a UX that flow isn't ideal.
