### ISSUE TITLE
React: signin does not trigger the session atom refresh

### ISSUE THREAD

**Issue by paulgirard** [better-auth/better-auth#87]
We are testing your library for a small tool.
We like very much the approach, thanks for creating and sharing that lib :pray: 

We are using it with react client-side (and tsoa server side) and we've just discovered that a successful call to signin.email does not trigger the session atom refresh action.
The signOut does.

I am surprised by such a behavior as I understood that the useSession should be the only source of truth.

By reading the source code I think this behavior is due to those lines:
 
```typescript
const atomListeners: AtomListener[] = [
		{
			signal: "_sessionSignal",
			matcher(path) {
				return (
					path === "/sign-out" ||
					path === "sign-up/email" ||
					path === "/user/update"
				);
			},
		},
	];
```
https://github.com/better-auth/better-auth/blob/main/packages/better-auth/src/client/config.ts#L36-L38

Looks like the only API calls which trigger a session refresh are `sign-out`, `sign-up` and `user/update`.
But I am not sure I understood the codebase correctly?

Is that in purpose that sign-in is not in that list?
If yes could someone explain the rational behind this choice?
If not should I propose a PR to add it?

**Comment by Bekacru** [comment]
Oh, 'sign-in' wasn't added, assuming there would be a redirection. It should definitely be there, and yes, feel free to open a PR. I would appreciate that!

**Comment by paulgirard** [comment]
Thanks for your very prompt reply.
I'll propose a PR beginning of next week as I am out for the week end.
Thanks again for your work

**Comment by Bekacru** [comment]
> Thanks for your very prompt reply. I'll propose a PR beginning of next week as I am out for the week end. Thanks again for your work

No worries. It should be added on the next release.

**Comment by Bekacru** [comment]
fixed on latest

**Comment by paulgirard** [comment]
I confirm that fixed the issue! Thank you.
