### ISSUE TITLE
useSession type not working properly

### ISSUE THREAD

**Issue by darklight9811** [better-auth/better-auth#871]
**Describe the bug**
The type for the useSession (on the frontend) is not working properly, it display data as never, the code works as expected returning the session and user data.

**To Reproduce**

1. Setup the auth client on react
2. Use the useSession in any component
3. Try to access any property from data inside useSession

**Expected behavior**
The session type to display user and session information

**Screenshots**
![image](https://github.com/user-attachments/assets/da163ef3-3d2c-492e-a2bb-4fba1828ec5d)

**Desktop (please complete the following information):**

- OS: windows 10
- Browser [e.g. chrome, safari] (not applicable)
- Version [e.g. 22] 1.0.18

**Comment by Bekacru** [comment]
could you please share what plugins you're using on the client?

**Comment by darklight9811** [comment]
@Bekacru no plugins

![image](https://github.com/user-attachments/assets/7a4f93dc-b382-4645-bce7-c1d7221e73d0)

**Comment by darklight9811** [comment]
I'm thinking it may be a typescript config, will try to debug this
