### ISSUE TITLE
Prisma Adapter: Cannot compile type declarations

### ISSUE THREAD

**Issue by ccssmnn** [better-auth/better-auth#899]
### Is this suited for github?

- [X] Yes, this is suited for github

### To Reproduce

```typescript
// auth.ts
import { PrismaClient } from "@prisma/client";
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

const prisma = new PrismaClient();

export const auth = betterAuth({ 
  database: prismaAdapter(prisma, { provider: "postgresql" }),
});
```

```json
// tsconfig.json
{
  "compilerOptions": {
    "declaration": true, // 👈 this one triggers the error
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "skipLibCheck": true,
    "strict": true,
    "target": "ESNext"
  }
}
```

### Current vs. Expected behavior

Compiling with tsc fails. `Exported variable 'auth' has or is using name 'PrismaConfig' from external module "my-project/node_modules/better-auth/dist/adapters/prisma" but cannot be named.`

### What version of Better Auth are you using?

1.0.21

### Provide environment information

```bash
Here is a Codesandbox that reproduces the error

https://codesandbox.io/p/devbox/276rrx
```

### Which area(s) are affected? (Select all that apply)

Types

### Auth config (if applicable)

```typescript
import { PrismaClient } from "@prisma/client";
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

const prisma = new PrismaClient();

export const auth = betterAuth({ 
  database: prismaAdapter(prisma, { provider: "postgresql" }),
});
```

### Additional context

I have a monorepo with a hono server and a vite client. The hono server exports a few modules that are used in the client to take advantage of Hono RPC and reuse a few zod schemas. To make this typesafe, I want to compile the exported modules with declarations. This bug does break the compilation and i cannot ignore the error because it is specifically related to generating type declarations.

**Comment by carlassmann** [comment]
exporting the interface `PrismaConfig` in the Prisma adapter fixes this issue.

**Comment by ping-maxwell** [comment]
Yeah, better auth doesn't work with declarations enabled:
https://www.better-auth.com/docs/concepts/typescript#typescript-config
