### ISSUE TITLE
User deletion flow is flawed: problems with UX and DX

### ISSUE THREAD

**Issue by JosipPardon** [better-auth/better-auth#926]
### Is this suited for github?

- [X] Yes, this is suited for github

### Current vs. Expected behavior

According to [docs](https://www.better-auth.com/docs/concepts/users-accounts#delete-user), recommended way of setting up user deletion feature is this:

1. Add `sendDeleteAccountVerification` to `betterAuth({...})` in `auth.ts`.
2. When user presses _delete account_, call `authClient.deleteUser()`, which triggers execution of `sendDeleteAccountVerification`
3. Inside `sendDeleteAccountVerification` send email with URL for account deletion, which is user expected to click: `sendEmail(data.user.email, "Verify Deletion", data.url)`

Problem is that this URL leads to API endpoint. When user opens it, he sees this:

![{FF16826C-6081-4B67-B5B7-DE2BA1AAED69}](https://github.com/user-attachments/assets/5afcb379-9181-4de7-be6b-1337f1898705)

Users should not be expected to visit API endpoints and open pages which are actually json objects, like one above.

My recommendation is this:

1. Rename `authClient.deleteUser()` to `authClient.sendUserDeletionToken()` because original name is misleading, but keep original functionality. 
2. Create new function `authClient.deleteUser({token: string})` which sends request to same URL described above, or deletes user in some other way.

So, flow should be similar as for email OTP (described [here](https://www.better-auth.com/docs/plugins/email-otp#send-otp)) - we have `authClient.emailOtp.sendVerificationOtp` and `authClient.signIn.emailOtp`.

If they want, inside `sendDeleteAccountVerification` developers can send user email with link to page which executes `authClient.deleteUser({token: string})` when opened. This is how link verification can be implemented.

### What version of Better Auth are you using?

1.0.21

**Comment by daveycodez** [comment]
Is it possible to delete users without needing email verification to do so?
