### ISSUE TITLE
Do not require `expo-secure-store` when providing custom storage

### ISSUE THREAD

**Issue by hyoban** [better-auth/better-auth#928]
### Is this suited for github?

- [x] Yes, this is suited for github

### Describe the solution you'd like

Just remove the dependency on `expo-secure-store` and let users configure it

### Describe alternatives you've considered

Only dynamically import `expo-secure-store` when no storage is provided

### Additional context

I am willing to submit a PR to fix this issue

**Comment by Bekacru** [comment]
Yeah, good suggestion. would appreciate a PR. I'm not sure if dynamic imports cause any issues with Metro. If they do, we could make the storage user defined. If not, it should be imported dynamically.

**Comment by hyoban** [comment]
I tried. Dynamic import works fine, but `await import` will make the plugin async.
