### ISSUE TITLE
better auth social providers type

### ISSUE THREAD

**Issue by draylegend** [better-auth/better-auth#934]
### Issue

```ts
TS2322: Type string is not assignable to type
'github' | 'apple' | 'discord' | 'facebook' | 'google' | 'microsoft' | 'spotify' | 'twitch' | 'twitter' | 'dropbox' | 'linkedin' | 'gitlab' | 'reddit'

auth-5DAdlxmK.d.ts(8131, 21): The expected type comes from property provider which is declared here on type

Prettify<{ provider: "github" | "apple" | "discord" | "facebook" | "google" | "microsoft" | "spotify" | "twitch" | "twitter" | "dropbox" | "linkedin" | "gitlab" | "reddit"; idToken?: { ...; } | undefined; callbackURL?: string | undefined; newUserCallbackURL?: string | undefined; errorCallbackURL?: string | undefined...
```

![image](https://github.com/user-attachments/assets/4ad07892-29ed-4f9d-92ab-0b7dcf8f991b)

### Describe the solution you'd like

I need the type `BetterAuthSocialProviders` or similar to properly annotate arguments/variables

```ts
  protected signInWith(provider: BetterAuthSocialProviders) {
    signIn.social({ provider });
  }
```

```ts
export type BetterAuthSocialProviders = 'google' | ...;
```

**Comment by emroot** [comment]
can you use this instead? 
auth being your auth config.
```
type Providers = keyof typeof auth.options.socialProviders;
```
This will return only the providers that you are actually using.

**Comment by daveycodez** [comment]
That would be doable but it would keep the application's codebase cleaner to have an import type SocialProviders coming out of the lib.

**Comment by emroot** [comment]
Yeah I think that would be great to have if you need all the providers but this approach will limit to only the providers you are actually using, less error prone for someone to use a provider that is not implemented.

**Comment by draylegend** [comment]
@emroot thank you! Actually even better than I could imagine! In fact I just need already configured providers reducing the providers' list.

@daveycodez interesting point. The extra line suggested by @emroot doesn't hurt me ^^
