### ISSUE TITLE
What distinguishes this project from authjs?

### ISSUE THREAD

**Issue by osdiab** [better-auth/better-auth#94]
I stumbled on this project, and while I see it is at an early beta stage, I am curious about the impetus for building this and how it is intended to differ from authjs which also intends to be framework agnostic, typescript friendly and pluggable. Once the docs are more fleshed out and the project a little more mature, this probably would be a worthwhile comparison. Thanks!

**Comment by Kinfe123** [comment]
![image](https://github.com/user-attachments/assets/c62a599b-54d6-44e3-b46a-fdb89f07161e)
please visit the [website](https://better-auth.com) for more info - we try to put as much as flexibility as possible as battery included auth solution  -  .. lemme know if you had doubt on mind ....

**Comment by Bekacru** [comment]
> ![image](https://github.com/user-attachments/assets/c62a599b-54d6-44e3-b46a-fdb89f07161e)
> 
> please visit the [website](https://better-auth.com) for more info - we try to put as much as flexibility as possible as battery included auth solution  -  .. lemme know if you had doubt on mind ....

No. I think he is suggesting we should have a section on the docs comparing other similar solution. Which we should have at some point.

**Comment by luksch42** [comment]
In my opinion, NextAuth/Auth.js is quite difficult to customize once you have more specific requirements. Additionally, I'm not sure if Auth.js will ever make it out of beta 🫣

**Comment by Kinfe123** [comment]
i just mentioned the website tho since we got most of the unique features settle up on that website section which is technically something to compared with

**Comment by Bekacru** [comment]
closing this in favor of #112

**Comment by osdiab** [comment]
> No. I think he is suggesting we should have a section on the docs comparing other similar solution. Which we should have at some point.

Indeed this is what I meant, and @Kinfe123 I read the website and literally everything in the screenshot you posted are things that AuthJS claims as well (with the difference being that that project has Vercel behind it and a large number of projects using it in production).

I made the issue since I genuinely don't know how to evaluate what makes better-auth unique, and I'm sure I'm not the only one. Maybe it's just that it's designed better, or that the maintainers are more committed, I don't know. But yeah, maybe a question to answer later on.

**Comment by balazsorban44** [comment]
> with the difference being that that project has Vercel behind it 

Clarification. There is currently no company behind the Auth.js project. https://authjs.dev/contributors#notes

Also

> Additionally, I'm not sure if Auth.js will ever make it out of beta 🫣

Me neither. 😄 But working on it.


PS.: Better Auth looks great! It's an inspiring project!
