### ISSUE TITLE
Automatically detect BASE_URL

### ISSUE THREAD

**Issue by AliMejbar** [better-auth/better-auth#967]
### Is this suited for github?

- [X] Yes, this is suited for github

### Is your feature request related to a problem? Please describe.

At the moment it's difficult to setup BASE_URL especially when using preview deployments. It'd be great if better-auth could automatically detect the BASE_URL.

### Describe the solution you'd like

Kind of what [Authjs](https://authjs.dev/) is doing.		

### Describe alternatives you've considered

Each time setting up a BASE_URL environnement variable for each deployement.

**Comment by Bekacru** [comment]
It does detect automatically. If you're deploying on vercel you can remove it.

**Comment by AliMejbar** [comment]
> It does detect automatically. If you're deploying on vercel you can remove it.

It does indeed I just didn't guess it from the docs section https://www.better-auth.com/docs/installation#set-environment-variables. Thank's for your quick response and help.
