### ISSUE TITLE
API resolved without sending a response for /api/auth/get-session, this may result in stalled requests.

### ISSUE THREAD

**Issue by daveycodez** [better-auth/better-auth#983]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

Integrate better-auth into a Next.js project with Pages Router and attempt to use get-session endpoint.

Get this message in console:
```shell
API resolved without sending a response for /api/auth/get-session, this may result in stalled requests.
```

### Current vs. Expected behavior

Never let API resolve without getting the request

### What version of Better Auth are you using?

1.0.22

### Provide environment information

```bash
Next.js pages router
```

### Which area(s) are affected? (Select all that apply)

Backend

**Comment by daveycodez** [comment]
Sorted it out.

The fix is to await the handler.

```ts
import { NextApiRequest, NextApiResponse } from "next"
import { toNodeHandler } from "better-auth/node"
import { auth } from "@/lib/auth"

export const config = {
    api: {
        bodyParser: false, // Disallow body parsing, we will parse it manually
    },
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    await toNodeHandler(auth.handler)(req, res)
}
```

You might want to update the docs to reflect this @Bekacru Also the docs are missing TypeScript types for the .ts example

**EDIT**

Way cleaner implementation:

/pages/api/auth/[...all].ts
```ts
import { toNodeHandler } from "better-auth/node"
import { auth } from "@/lib/auth"

// Disallow body parsing, we will parse it manually
export const config = { api: { bodyParser: false } }

export default toNodeHandler(auth.handler)
```

**Comment by Bekacru** [comment]
thanks will update the docs!

**Comment by Bekacru** [comment]
updated
