### ISSUE TITLE
Email Verification isn't logging the user in

### ISSUE THREAD

**Issue by daveycodez** [better-auth/better-auth#996]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

Click an email verification link, and you have to enter the email and password again.

### Current vs. Expected behavior

Email Verification link should act like a magic link and log the user in

### What version of Better Auth are you using?

1.1.2

### Provide environment information

```bash
Nextjs
```

### Which area(s) are affected? (Select all that apply)

Client

**Comment by Bekacru** [comment]
you need to set `emailVerification.autoSignInAfterVerification` to sign in after verification.

**Comment by daveycodez** [comment]
Hmm I tried that option and it doesn't seem to be working. I am using anonymous users as well so maybe that is affecting it somehow?

```ts
    emailAndPassword: { enabled: true, requireEmailVerification: true },
    emailVerification: {
        sendVerificationEmail: async ({ user, url, token }, request) => {
            await resend.emails.send({
                from: "NEW-TECH <noreply@auth.newtech.dev>",
                to: user.email,
                subject: "Verify your email address",
                react: EmailTemplate({ preview: "Verify Email", content: "Click the button below to verify your email.", action: "Vefify Email", confirmationUrl: url })
            })
        },
        autoSignInAfterVerification: true,
        sendOnSignUp: true
    },
```

**Comment by daveycodez** [comment]
I figured out it's because I have this hook in my header

```ts
  useEffect(() => {
        if (!session && !isPending) {
            authClient.signIn.anonymous()
        }
    }, [session, isPending])
```

I'm using RLS through Neon and I need anonymous JWT keys so my fix right now is to log in every user as an anonymous user

**Comment by daveycodez** [comment]
What's weird though is magic link isn't giving me this issue

**Comment by daveycodez** [comment]
Okay I've verified that it is not working if you are currently logged in as an anonymous user, it should trigger the accounts merging like a normal login or sign up. Magic Link isn't having this issue.

**Comment by Bekacru** [comment]
that is cause it only applies if there is no active session at the time of verification. Verification isn't exactly a magic link or a way of signing in, so it doesn't override the current session or link an existing anonymous account upon verification.

**Comment by daveycodez** [comment]
Need a way for email verification to also function as a magic link, or to just have the email verification trigger send the magic link instead. Otherwise this makes the anonymous users feature unusable

**Comment by Bekacru** [comment]
hmm why not send them a magic link?

**Comment by daveycodez** [comment]
Well it still needs to require email verification on signup, so signup with password needs to return a null token

**Comment by Bekacru** [comment]
yeah actually you're right. It make sense to log them in on anonymous case. if verification is required it'd be a blocker.

**Comment by Bekacru** [comment]
we'll generate new session if the email don't match on verification

**Comment by daveycodez** [comment]
Yea also to note, Magic Link isn't working if the email isn't verified and requireVerification is true. Magic Link should verify the email of an unverified email account on click. Magic Link & Email Verification function should be pretty much identical except for the text written in the email
